# Báo cáo tài chính chuẩn hoá FireAnt (financial-data)

Bộ chỉ tiêu "3 trong 1" từ `restv2.fireant.vn/symbols/{ticker}/financial-data`: CĐKT + KQKD +
LCTT đã gộp và chuẩn hoá sẵn thành **một dòng một kỳ**, kèm chỉ số định giá (P/E, P/B, EV/EBITDA),
sinh lời (ROE, ROA, ROIC), tăng trưởng, số liệu trung bình ngành, Piotroski F-Score và
Altman Z-Score — khác với `full-financial-reports` (bảng dài, chỉ tiêu thô theo cây phân cấp)
mà `Fireant.get_financials` đang dùng.

Lưu vào `fscore.db`, **giữ nguyên tên trường của API làm tên cột**. Bộ trường phụ thuộc loại hình
doanh nghiệp nên mỗi loại một bảng, khoá `(symbol, period)`:

| bảng | loại hình | số trường |
|---|---|---|
| `fireant_financial_data_general` | General | 340 |
| `fireant_financial_data_bank` | Bank | 298 |
| `fireant_financial_data_securities` | Securities | 449 |
| `fireant_financial_data_insurance` | Insurance | 419 |

Vì sao tách bảng: giữa các loại hình có tên trường chỉ khác nhau ở chữ hoa/thường
(`ShortTermPrepaidExpense` vs `ShorttermPrepaidExpense`), mà SQLite **không phân biệt hoa thường**
ở tên cột nên không nhét chung một bảng được.

Cột `period` dùng chung nhãn kỳ với các bảng `fireant_*` khác: `'2025'` (năm) hoặc `'Q1-2026'`
(quý), nên dữ liệu năm và quý nằm chung bảng mà không đụng khoá.

In [1]:
from fireant_connector import Fireant
import pandas as pd
import sqlite3

# financial-data hỗ trợ cả ngân hàng / chứng khoán / bảo hiểm (mỗi loại một bảng)
# nên crawl toàn bộ danh sách mã, không lọc phi tài chính như notebook fireant.ipynb
tickers = pd.read_csv('./data/tickers_all.csv')
tickers

,ID,Symbol,CompanyName,Exchange,IndustryName1,IndustryName2,IndustryName3,FirstTradeDate,BeforeExchange,DelistedReason,IsTerminated
0,4712.0,A32,CTCP 32,UPCOM,Tiêu dùng không thiết yếu,Thời trang và hàng lâu bền,Thời trang và dệt may,2018-10-22 17:00:00,NaN,NaN,False
1,2541.0,AAA,CTCP Nhựa An Phát Xanh,HOSE,Nguyên vật liệu,Nguyên vật liệu,Hóa chất,2016-11-24 17:00:00,HNX,"AAA: Ngày 18/11/2016, ngày hủy niêm yết cổ phi...",False
2,5601.0,AAH,CTCP Hợp Nhất,UPCOM,Năng lượng,Năng lượng,Dầu khí,2024-01-10 17:00:00,NaN,NaN,False
3,1813.0,AAM,CTCP Thủy sản MeKong,HOSE,Tiêu dùng thiết yếu,"Thực phẩm, đồ uống và thuốc lá",Thực phẩm,2009-09-23 17:00:00,NaN,NaN,False
4,5816.0,AAN,CTCP Lương thực A An,HOSE,Tiêu dùng thiết yếu,"Thực phẩm, đồ uống và thuốc lá",Thực phẩm,2026-05-21 17:00:00,NaN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...
2044,NaN,VFW,Công ty Cổ phần Quản lý quỹ Lộc Việt,OTC,NaN,NaN,NaN,NaN,NaN,NaN,True
2045,NaN,VHW,CTCP Nước Khoáng Vĩnh Hảo,OTC,NaN,Hàng tiêu dùng,NaN,NaN,NaN,NaN,True
2046,NaN,VLD,Công ty Cổ phần Bất Động Sản Viettronics,OTC,NaN,NaN,NaN,NaN,NaN,NaN,True
2047,NaN,VTT,NaN,HNX,NaN,NaN,NaN,NaN,NaN,NaN,True
2048,NaN,YAN,CTCP Công nghệ và Tầm nhìn Yêu âm nhạc,OTC,NaN,Dịch vụ,NaN,NaN,NaN,NaN,True

In [2]:
symbols = tickers['Symbol'].dropna().unique().tolist()
len(symbols)

2049

## Thử một mã trước

API **bắt buộc** tham số `count` và **không có tham số neo năm** — luôn trả `count` kỳ gần nhất
rồi tự cắt khi hết dữ liệu (HPG xin 100 kỳ chỉ ra 22 kỳ, 2025 → 2004). `get_financial_data` tự
tính `count` từ **năm hiện tại** (không phải `end_year`) rồi lọc lại theo `start_year`.

In [3]:
fa = Fireant(request_sleep=0.2)

hpg = fa.get_financial_data('HPG', start_year=2009)
print(hpg.shape, '->', len(hpg), 'kỳ x', hpg.shape[1] - 2, 'trường + symbol/period')
hpg[['symbol', 'period', 'CompanyType', 'NetSale', 'ProfitAfterTax',
     'TotalAsset', 'ROE', 'PE', 'PB', 'PiotroskiFScore', 'ManufacturingZScore']]

HPG financial-data NAM: xin 19 ky (>= 2009)

(17, 342) -> 17 kỳ x 340 trường + symbol/period

,symbol,period,CompanyType,NetSale,ProfitAfterTax,TotalAsset,ROE,PE,PB,PiotroskiFScore,ManufacturingZScore
0,HPG,2009,General,8123394614746,1270706623417,10243239989085,0.27149,9.03169,2.38074,4,2.88218
1,HPG,2010,General,14267083816361,1376316086778,14903658232099,0.22864,9.11633,1.92257,3,2.50832
2,HPG,2011,General,17851896561575,1296850503678,17524683026075,0.1682,4.43882,0.74029,4,2.10407
3,HPG,2012,General,16826851892984,1030505429517,19015763461546,0.12019,8.85301,1.08843,4,1.97564
4,HPG,2013,General,18934292150531,2010435402769,23076377862689,0.21517,8.81341,1.81289,8,2.2071
5,HPG,2014,General,25525348822713,3250214590204,22089104397803,0.29178,8.12312,2.16524,7,3.69145
6,HPG,2015,General,27452932114333,3504382487779,25506769185545,0.26373,6.13982,1.48161,7,3.18201
7,HPG,2016,General,33283210159987,6606202726929,33226552317885,0.38477,5.50815,1.84179,7,4.04817
8,HPG,2017,General,46161691614304,8014756586048,53022184778251,0.30649,8.876,2.20111,4,4.22813
9,HPG,2018,General,55836458379759,8600550706227,78223007670925,0.23481,7.66766,1.62325,2,2.52143
10,HPG,2019,General,63658192673791,7578248236229,101776030099900,0.17029,8.61983,1.36246,4,1.93037
11,HPG,2020,General,90118503426717,13506164056907,131511434388837,0.25139,10.21059,2.32492,6,2.54029
12,HPG,2021,General,149679789979345,34520954931298,178236422358249,0.45971,6.01957,2.29012,7,3.46306
13,HPG,2022,General,141409274460632,8444429054516,170335521637132,0.09078,12.3376,1.09019,5,2.33324
14,HPG,2023,General,118953027893654,6800388315081,187782586563801,0.06871,23.77787,1.58142,4,2.35496
15,HPG,2024,General,138855112131387,12020023621271,224489707553981,0.11055,14.17967,1.4906,5,2.15447
16,HPG,2025,General,156116094618482,15514931571606,257899200817547,0.1257,13.11267,1.56859,6,2.15631

## Crawl toàn bộ

`skip_existing=True` bỏ qua mã đã có trong DB nên chạy lại được sau khi đứt giữa chừng; mọi lỗi
của một mã chỉ được ghi vào log chứ không làm dừng cả đợt, và Ctrl+C vẫn trả về phần đã chạy.

In [4]:
log = fa.crawl_financial_data_to_db(
    symbols,
    start_year=2009,
    type_time='NAM',
    db_path='fscore.db',
    skip_existing=True,
    log_path='./logs/fireant_financial_data.csv',
    sleep=0.3,
)
log

A32 financial-data NAM: xin 19 ky (>= 2009)
Da luu 10 ky (A32) vao cafef.db.fireant_financial_data_general
(1/2049) A32 xong (10 ky)
AAA financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (AAA) vao cafef.db.fireant_financial_data_general
(2/2049) AAA xong (17 ky)
AAH financial-data NAM: xin 19 ky (>= 2009)
Da luu 7 ky (AAH) vao cafef.db.fireant_financial_data_general
(3/2049) AAH xong (7 ky)
AAM financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (AAM) vao cafef.db.fireant_financial_data_general
(4/2049) AAM xong (17 ky)
AAN financial-data NAM: xin 19 ky (>= 2009)
Da luu 2 ky (AAN) vao cafef.db.fireant_financial_data_general
(5/2049) AAN xong (2 ky)
AAS financial-data NAM: xin 19 ky (>= 2009)
Da luu 10 ky (AAS) vao cafef.db.fireant_financial_data_securities
(6/2049) AAS xong (10 ky)
AAT financial-data NAM: xin 19 ky (>= 2009)
Da luu 8 ky (AAT) vao cafef.db.fireant_financial_data_general
(7/2049) AAT xong (8 ky)
AAV financial-data NAM: xin 19 ky (>= 2009)
Da luu 12 ky (AAV) vao cafef.db.fireant_financial_data_general
(8/2049) AAV xong (12 ky)
ABB financial-data NAM: xin 19 ky (>= 2009)
Da luu 15 ky (ABB) vao cafef.db.fireant_financial_data_bank
(9/2049) ABB xong (15 ky)
ABC financial-data NAM: xin 19 ky (>= 2009)
Da luu 16 ky (ABC) vao cafef.db.fireant_financial_data_general
(10/2049) ABC xong (16 ky)
ABI financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (ABI) vao cafef.db.fireant_financial_data_insurance
(11/2049) ABI xong (17 ky)
ABR financial-data NAM: xin 19 ky (>= 2009)
Da luu 10 ky (ABR) vao cafef.db.fireant_financial_data_general
(12/2049) ABR xong (10 ky)
ABS financial-data NAM: xin 19 ky (>= 2009)
Da luu 9 ky (ABS) vao cafef.db.fireant_financial_data_general
(13/2049) ABS xong (9 ky)
ABT financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (ABT) vao cafef.db.fireant_financial_data_general
(14/2049) ABT xong (17 ky)
ABW financial-data NAM: xin 19 ky (>= 2009)
Da luu 6 ky (ABW) vao cafef.db.fireant_financial_data_securities
(15/2049) ABW xong (6 ky)
ACB financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (ACB) vao cafef.db.fireant_financial_data_bank
(16/2049) ACB xong (17 ky)
ACC financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (ACC) vao cafef.db.fireant_financial_data_general
(17/2049) ACC xong (17 ky)
ACE financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (ACE) vao cafef.db.fireant_financial_data_general
(18/2049) ACE xong (17 ky)
ACG financial-data NAM: xin 19 ky (>= 2009)
Da luu 8 ky (ACG) vao cafef.db.fireant_financial_data_general
(19/2049) ACG xong (8 ky)
ACL financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (ACL) vao cafef.db.fireant_financial_data_general
(20/2049) ACL xong (17 ky)
ACM financial-data NAM: xin 19 ky (>= 2009)
Da luu 13 ky (ACM) vao cafef.db.fireant_financial_data_general
(21/2049) ACM xong (13 ky)
ACS financial-data NAM: xin 19 ky (>= 2009)
Da luu 10 ky (ACS) vao cafef.db.fireant_financial_data_general
(22/2049) ACS xong (10 ky)
ACV financial-data NAM: xin 19 ky (>= 2009)
Da luu 15 ky (ACV) vao cafef.db.fireant_financial_data_general
(23/2049) ACV xong (15 ky)
ADC financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (ADC) vao cafef.db.fireant_financial_data_general
(24/2049) ADC xong (17 ky)
ADG financial-data NAM: xin 19 ky (>= 2009)
Da luu 10 ky (ADG) vao cafef.db.fireant_financial_data_general
(25/2049) ADG xong (10 ky)
ADP financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (ADP) vao cafef.db.fireant_financial_data_general
(26/2049) ADP xong (17 ky)
ADS financial-data NAM: xin 19 ky (>= 2009)
Da luu 13 ky (ADS) vao cafef.db.fireant_financial_data_general
(27/2049) ADS xong (13 ky)
AFX financial-data NAM: xin 19 ky (>= 2009)
Da luu 15 ky (AFX) vao cafef.db.fireant_financial_data_general
(28/2049) AFX xong (15 ky)
AG1 financial-data NAM: xin 19 ky (>= 2009)
Da luu 11 ky (AG1) vao cafef.db.fireant_financial_data_general
(29/2049) AG1 xong (11 ky)
AGF financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (AGF) vao cafef.db.fireant_financial_data_general
(30/2049) AGF xong (17 ky)
AGG financial-data NAM: xin 19 ky (>= 2009)
Da luu 10 ky (AGG) vao cafef.db.fireant_financial_data_general
(31/2049) AGG xong (10 ky)
AGM financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (AGM) vao cafef.db.fireant_financial_data_general
(32/2049) AGM xong (17 ky)
AGP financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (AGP) vao cafef.db.fireant_financial_data_general
(33/2049) AGP xong (17 ky)
AGR financial-data NAM: xin 19 ky (>= 2009)
Da luu 12 ky (AGR) vao cafef.db.fireant_financial_data_securities
(34/2049) AGR xong (12 ky)
AGX financial-data NAM: xin 19 ky (>= 2009)
Da luu 16 ky (AGX) vao cafef.db.fireant_financial_data_general
(35/2049) AGX xong (16 ky)
AIC financial-data NAM: xin 19 ky (>= 2009)
Da luu 10 ky (AIC) vao cafef.db.fireant_financial_data_insurance
(36/2049) AIC xong (10 ky)
AIG financial-data NAM: xin 19 ky (>= 2009)
Da luu 8 ky (AIG) vao cafef.db.fireant_financial_data_general
(37/2049) AIG xong (8 ky)
ALC financial-data NAM: xin 19 ky (>= 2009)
Da luu 11 ky (ALC) vao cafef.db.fireant_financial_data_general
(38/2049) ALC xong (11 ky)
ALT financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (ALT) vao cafef.db.fireant_financial_data_general
(39/2049) ALT xong (17 ky)
ALV financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (ALV) vao cafef.db.fireant_financial_data_general
(40/2049) ALV xong (17 ky)
AMC financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (AMC) vao cafef.db.fireant_financial_data_general
(41/2049) AMC xong (17 ky)
AME financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (AME) vao cafef.db.fireant_financial_data_general
(42/2049) AME xong (17 ky)
AMP financial-data NAM: xin 19 ky (>= 2009)
Da luu 15 ky (AMP) vao cafef.db.fireant_financial_data_general
(43/2049) AMP xong (15 ky)
AMS financial-data NAM: xin 19 ky (>= 2009)
Da luu 15 ky (AMS) vao cafef.db.fireant_financial_data_general
(44/2049) AMS xong (15 ky)
AMV financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (AMV) vao cafef.db.fireant_financial_data_general
(45/2049) AMV xong (17 ky)
ANI financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (ANI) vao cafef.db.fireant_financial_data_general
(46/2049) ANI xong (17 ky)
ANT financial-data NAM: xin 19 ky (>= 2009)
Da luu 15 ky (ANT) vao cafef.db.fireant_financial_data_general
(47/2049) ANT xong (15 ky)
ANV financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (ANV) vao cafef.db.fireant_financial_data_general
(48/2049) ANV xong (17 ky)
APC financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (APC) vao cafef.db.fireant_financial_data_general
(49/2049) APC xong (17 ky)
APF financial-data NAM: xin 19 ky (>= 2009)
Da luu 14 ky (APF) vao cafef.db.fireant_financial_data_general
(50/2049) APF xong (14 ky)
APG financial-data NAM: xin 19 ky (>= 2009)
Da luu 12 ky (APG) vao cafef.db.fireant_financial_data_securities
(51/2049) APG xong (12 ky)
APH financial-data NAM: xin 19 ky (>= 2009)
Da luu 9 ky (APH) vao cafef.db.fireant_financial_data_general
(52/2049) APH xong (9 ky)
API financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (API) vao cafef.db.fireant_financial_data_general
(53/2049) API xong (17 ky)
APL financial-data NAM: xin 19 ky (>= 2009)
Da luu 12 ky (APL) vao cafef.db.fireant_financial_data_general
(54/2049) APL xong (12 ky)
APP financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (APP) vao cafef.db.fireant_financial_data_general
(55/2049) APP xong (17 ky)
APS financial-data NAM: xin 19 ky (>= 2009)
Da luu 12 ky (APS) vao cafef.db.fireant_financial_data_securities
(56/2049) APS xong (12 ky)
APT financial-data NAM: xin 19 ky (>= 2009)
Da luu 10 ky (APT) vao cafef.db.fireant_financial_data_general
(57/2049) APT xong (10 ky)
ARM financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (ARM) vao cafef.db.fireant_financial_data_general
(58/2049) ARM xong (17 ky)
ART financial-data NAM: xin 19 ky (>= 2009)
Da luu 12 ky (ART) vao cafef.db.fireant_financial_data_securities
(59/2049) ART xong (12 ky)
ASG financial-data NAM: xin 19 ky (>= 2009)
Da luu 9 ky (ASG) vao cafef.db.fireant_financial_data_general
(60/2049) ASG xong (9 ky)
ASM financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (ASM) vao cafef.db.fireant_financial_data_general
(61/2049) ASM xong (17 ky)
ASP financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (ASP) vao cafef.db.fireant_financial_data_general
(62/2049) ASP xong (17 ky)
AST financial-data NAM: xin 19 ky (>= 2009)
Da luu 11 ky (AST) vao cafef.db.fireant_financial_data_general
(63/2049) AST xong (11 ky)
ATA financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (ATA) vao cafef.db.fireant_financial_data_general
(64/2049) ATA xong (17 ky)
ATG financial-data NAM: xin 19 ky (>= 2009)
Da luu 13 ky (ATG) vao cafef.db.fireant_financial_data_general
(65/2049) ATG xong (13 ky)
ATS financial-data NAM: xin 19 ky (>= 2009)
Da luu 13 ky (ATS) vao cafef.db.fireant_financial_data_general
(66/2049) ATS xong (13 ky)
AVC financial-data NAM: xin 19 ky (>= 2009)
Da luu 12 ky (AVC) vao cafef.db.fireant_financial_data_general
(67/2049) AVC xong (12 ky)
AVG financial-data NAM: xin 19 ky (>= 2009)
Da luu 5 ky (AVG) vao cafef.db.fireant_financial_data_general
(68/2049) AVG xong (5 ky)
BAB financial-data NAM: xin 19 ky (>= 2009)
Da luu 14 ky (BAB) vao cafef.db.fireant_financial_data_bank
(69/2049) BAB xong (14 ky)
BAF financial-data NAM: xin 19 ky (>= 2009)
Da luu 8 ky (BAF) vao cafef.db.fireant_financial_data_general
(70/2049) BAF xong (8 ky)
BAL financial-data NAM: xin 19 ky (>= 2009)
Da luu 12 ky (BAL) vao cafef.db.fireant_financial_data_general
(71/2049) BAL xong (12 ky)
BAX financial-data NAM: xin 19 ky (>= 2009)
Da luu 16 ky (BAX) vao cafef.db.fireant_financial_data_general
(72/2049) BAX xong (16 ky)
BBH financial-data NAM: xin 19 ky (>= 2009)
Da luu 8 ky (BBH) vao cafef.db.fireant_financial_data_general
(73/2049) BBH xong (8 ky)
BBM financial-data NAM: xin 19 ky (>= 2009)
Da luu 11 ky (BBM) vao cafef.db.fireant_financial_data_general
(74/2049) BBM xong (11 ky)
BBS financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (BBS) vao cafef.db.fireant_financial_data_general
(75/2049) BBS xong (17 ky)
BBT financial-data NAM: xin 19 ky (>= 2009)
Da luu 14 ky (BBT) vao cafef.db.fireant_financial_data_general
(76/2049) BBT xong (14 ky)
BCA financial-data NAM: xin 19 ky (>= 2009)
Da luu 7 ky (BCA) vao cafef.db.fireant_financial_data_general
(77/2049) BCA xong (7 ky)
BCB financial-data NAM: xin 19 ky (>= 2009)
Da luu 8 ky (BCB) vao cafef.db.fireant_financial_data_general
(78/2049) BCB xong (8 ky)
BCC financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (BCC) vao cafef.db.fireant_financial_data_general
(79/2049) BCC xong (17 ky)
BCE financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (BCE) vao cafef.db.fireant_financial_data_general
(80/2049) BCE xong (17 ky)
BCF financial-data NAM: xin 19 ky (>= 2009)
Da luu 11 ky (BCF) vao cafef.db.fireant_financial_data_general
(81/2049) BCF xong (11 ky)
BCG financial-data NAM: xin 19 ky (>= 2009)
Da luu 13 ky (BCG) vao cafef.db.fireant_financial_data_general
(82/2049) BCG xong (13 ky)
BCM financial-data NAM: xin 19 ky (>= 2009)
Da luu 11 ky (BCM) vao cafef.db.fireant_financial_data_general
(83/2049) BCM xong (11 ky)
BCP financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (BCP) vao cafef.db.fireant_financial_data_general
(84/2049) BCP xong (17 ky)
BCR financial-data NAM: xin 19 ky (>= 2009)
Da luu 5 ky (BCR) vao cafef.db.fireant_financial_data_general
(85/2049) BCR xong (5 ky)
BCV financial-data NAM: xin 19 ky (>= 2009)
Da luu 8 ky (BCV) vao cafef.db.fireant_financial_data_general
(86/2049) BCV xong (8 ky)
BDG financial-data NAM: xin 19 ky (>= 2009)
Da luu 12 ky (BDG) vao cafef.db.fireant_financial_data_general
(87/2049) BDG xong (12 ky)
BDT financial-data NAM: xin 19 ky (>= 2009)
Da luu 11 ky (BDT) vao cafef.db.fireant_financial_data_general
(88/2049) BDT xong (11 ky)
BDW financial-data NAM: xin 19 ky (>= 2009)
Da luu 13 ky (BDW) vao cafef.db.fireant_financial_data_general
(89/2049) BDW xong (13 ky)
BED financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (BED) vao cafef.db.fireant_financial_data_general
(90/2049) BED xong (17 ky)
BEL financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (BEL) vao cafef.db.fireant_financial_data_general
(91/2049) BEL xong (17 ky)
BFC financial-data NAM: xin 19 ky (>= 2009)
Da luu 15 ky (BFC) vao cafef.db.fireant_financial_data_general
(92/2049) BFC xong (15 ky)
BGE financial-data NAM: xin 19 ky (>= 2009)
Da luu 4 ky (BGE) vao cafef.db.fireant_financial_data_general
(93/2049) BGE xong (4 ky)
BGW financial-data NAM: xin 19 ky (>= 2009)
Da luu 13 ky (BGW) vao cafef.db.fireant_financial_data_general
(94/2049) BGW xong (13 ky)
BHA financial-data NAM: xin 19 ky (>= 2009)
Da luu 11 ky (BHA) vao cafef.db.fireant_financial_data_general
(95/2049) BHA xong (11 ky)
BHC financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (BHC) vao cafef.db.fireant_financial_data_general
(96/2049) BHC xong (17 ky)
BHG financial-data NAM: xin 19 ky (>= 2009)
Da luu 10 ky (BHG) vao cafef.db.fireant_financial_data_general
(97/2049) BHG xong (10 ky)
BHH financial-data NAM: xin 19 ky (>= 2009)
Da luu 2 ky (BHH) vao cafef.db.fireant_financial_data_general
(98/2049) BHH xong (2 ky)
BHI financial-data NAM: xin 19 ky (>= 2009)
Da luu 8 ky (BHI) vao cafef.db.fireant_financial_data_insurance
(99/2049) BHI xong (8 ky)
BHK financial-data NAM: xin 19 ky (>= 2009)
Da luu 10 ky (BHK) vao cafef.db.fireant_financial_data_general
(100/2049) BHK xong (10 ky)
BHN financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (BHN) vao cafef.db.fireant_financial_data_general
(101/2049) BHN xong (17 ky)
BHP financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (BHP) vao cafef.db.fireant_financial_data_general
(102/2049) BHP xong (17 ky)
BIC financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (BIC) vao cafef.db.fireant_financial_data_insurance
(103/2049) BIC xong (17 ky)
BID financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (BID) vao cafef.db.fireant_financial_data_bank
(104/2049) BID xong (17 ky)
BIG financial-data NAM: xin 19 ky (>= 2009)
Da luu 7 ky (BIG) vao cafef.db.fireant_financial_data_general
(105/2049) BIG xong (7 ky)
BIO financial-data NAM: xin 19 ky (>= 2009)
Da luu 10 ky (BIO) vao cafef.db.fireant_financial_data_general
(106/2049) BIO xong (10 ky)
BKC financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (BKC) vao cafef.db.fireant_financial_data_general
(107/2049) BKC xong (17 ky)
BKG financial-data NAM: xin 19 ky (>= 2009)
Da luu 9 ky (BKG) vao cafef.db.fireant_financial_data_general
(108/2049) BKG xong (9 ky)
BLF financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (BLF) vao cafef.db.fireant_financial_data_general
(109/2049) BLF xong (17 ky)
BLI financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (BLI) vao cafef.db.fireant_financial_data_insurance
(110/2049) BLI xong (17 ky)
BLN financial-data NAM: xin 19 ky (>= 2009)
Da luu 11 ky (BLN) vao cafef.db.fireant_financial_data_general
(111/2049) BLN xong (11 ky)
BLT financial-data NAM: xin 19 ky (>= 2009)
Da luu 13 ky (BLT) vao cafef.db.fireant_financial_data_general
(112/2049) BLT xong (13 ky)
BMC financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (BMC) vao cafef.db.fireant_financial_data_general
(113/2049) BMC xong (17 ky)
BMD financial-data NAM: xin 19 ky (>= 2009)
Da luu 11 ky (BMD) vao cafef.db.fireant_financial_data_general
(114/2049) BMD xong (11 ky)
BMF financial-data NAM: xin 19 ky (>= 2009)
Da luu 10 ky (BMF) vao cafef.db.fireant_financial_data_general
(115/2049) BMF xong (10 ky)
BMG financial-data NAM: xin 19 ky (>= 2009)
Da luu 10 ky (BMG) vao cafef.db.fireant_financial_data_general
(116/2049) BMG xong (10 ky)
BMI financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (BMI) vao cafef.db.fireant_financial_data_insurance
(117/2049) BMI xong (17 ky)
BMJ financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (BMJ) vao cafef.db.fireant_financial_data_general
(118/2049) BMJ xong (17 ky)
BMK financial-data NAM: xin 19 ky (>= 2009)
Da luu 1 ky (BMK) vao cafef.db.fireant_financial_data_general
(119/2049) BMK xong (1 ky)
BMP financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (BMP) vao cafef.db.fireant_financial_data_general
(120/2049) BMP xong (17 ky)
BMS financial-data NAM: xin 19 ky (>= 2009)
Da luu 10 ky (BMS) vao cafef.db.fireant_financial_data_securities
(121/2049) BMS xong (10 ky)
BMV financial-data NAM: xin 19 ky (>= 2009)
Da luu 11 ky (BMV) vao cafef.db.fireant_financial_data_general
(122/2049) BMV xong (11 ky)
BNA financial-data NAM: xin 19 ky (>= 2009)
Da luu 9 ky (BNA) vao cafef.db.fireant_financial_data_general
(123/2049) BNA xong (9 ky)
BNW financial-data NAM: xin 19 ky (>= 2009)
Da luu 10 ky (BNW) vao cafef.db.fireant_financial_data_general
(124/2049) BNW xong (10 ky)
BOT financial-data NAM: xin 19 ky (>= 2009)
Da luu 10 ky (BOT) vao cafef.db.fireant_financial_data_general
(125/2049) BOT xong (10 ky)
BPC financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (BPC) vao cafef.db.fireant_financial_data_general
(126/2049) BPC xong (17 ky)
BQB financial-data NAM: xin 19 ky (>= 2009)
Da luu 11 ky (BQB) vao cafef.db.fireant_financial_data_general
(127/2049) BQB xong (11 ky)
BQP financial-data NAM: xin 19 ky (>= 2009)
Da luu 1 ky (BQP) vao cafef.db.fireant_financial_data_general
(128/2049) BQP xong (1 ky)
BRC financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (BRC) vao cafef.db.fireant_financial_data_general
(129/2049) BRC xong (17 ky)
BRR financial-data NAM: xin 19 ky (>= 2009)
Da luu 10 ky (BRR) vao cafef.db.fireant_financial_data_general
(130/2049) BRR xong (10 ky)
BRS financial-data NAM: xin 19 ky (>= 2009)
Da luu 13 ky (BRS) vao cafef.db.fireant_financial_data_general
(131/2049) BRS xong (13 ky)
BSA financial-data NAM: xin 19 ky (>= 2009)
Da luu 12 ky (BSA) vao cafef.db.fireant_financial_data_general
(132/2049) BSA xong (12 ky)
BSD financial-data NAM: xin 19 ky (>= 2009)
Da luu 13 ky (BSD) vao cafef.db.fireant_financial_data_general
(133/2049) BSD xong (13 ky)
BSG financial-data NAM: xin 19 ky (>= 2009)
Da luu 12 ky (BSG) vao cafef.db.fireant_financial_data_general
(134/2049) BSG xong (12 ky)
BSH financial-data NAM: xin 19 ky (>= 2009)
Da luu 11 ky (BSH) vao cafef.db.fireant_financial_data_general
(135/2049) BSH xong (11 ky)
BSI financial-data NAM: xin 19 ky (>= 2009)
Da luu 12 ky (BSI) vao cafef.db.fireant_financial_data_securities
(136/2049) BSI xong (12 ky)
BSL financial-data NAM: xin 19 ky (>= 2009)
Da luu 11 ky (BSL) vao cafef.db.fireant_financial_data_general
(137/2049) BSL xong (11 ky)
BSP financial-data NAM: xin 19 ky (>= 2009)
Da luu 12 ky (BSP) vao cafef.db.fireant_financial_data_general
(138/2049) BSP xong (12 ky)
BSQ financial-data NAM: xin 19 ky (>= 2009)
Da luu 16 ky (BSQ) vao cafef.db.fireant_financial_data_general
(139/2049) BSQ xong (16 ky)
BSR financial-data NAM: xin 19 ky (>= 2009)
Da luu 13 ky (BSR) vao cafef.db.fireant_financial_data_general
(140/2049) BSR xong (13 ky)
BT1 financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (BT1) vao cafef.db.fireant_financial_data_general
(141/2049) BT1 xong (17 ky)
BT6 financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (BT6) vao cafef.db.fireant_financial_data_general
(142/2049) BT6 xong (17 ky)
BTB financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (BTB) vao cafef.db.fireant_financial_data_general
(143/2049) BTB xong (17 ky)
BTD financial-data NAM: xin 19 ky (>= 2009)
Da luu 12 ky (BTD) vao cafef.db.fireant_financial_data_general
(144/2049) BTD xong (12 ky)
BTG financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (BTG) vao cafef.db.fireant_financial_data_general
(145/2049) BTG xong (17 ky)
BTH financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (BTH) vao cafef.db.fireant_financial_data_general
(146/2049) BTH xong (17 ky)
BTN financial-data NAM: xin 19 ky (>= 2009)
Da luu 11 ky (BTN) vao cafef.db.fireant_financial_data_general
(147/2049) BTN xong (11 ky)
BTP financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (BTP) vao cafef.db.fireant_financial_data_general
(148/2049) BTP xong (17 ky)
BTS financial-data NAM: xin 19 ky (>= 2009)
Da luu 17 ky (BTS) vao cafef.db.fireant_financial_data_general
(149/2049) BTS xong (17 ky)

     Symbol  IsSuccess  Periods CompanyType      ErrorMessage
0       A32       True       10     General               NaN
1       AAA       True       17     General               NaN
2       AAH       True        7     General               NaN
3       AAM       True       17     General               NaN
4       AAN       True        2     General               NaN
...     ...        ...      ...         ...               ...
2044    VFW       True        0         NaN  Khong co du lieu
2045    VHW       True        0         NaN  Khong co du lieu
2046    VLD       True        0         NaN  Khong co du lieu
2047    VTT       True        0         NaN  Khong co du lieu
2048    YAN       True        0         NaN  Khong co du lieu

[2049 rows x 5 columns]

In [5]:
# mã lỗi / mã không có dữ liệu
log[~log['IsSuccess'] | (log['Periods'] == 0)]

        Symbol  IsSuccess  Periods CompanyType      ErrorMessage
398   E1VFVN30       True        0         NaN  Khong co du lieu
443   FUCTVGF3       True        0         NaN  Khong co du lieu
444   FUCTVGF4       True        0         NaN  Khong co du lieu
445   FUCTVGF5       True        0         NaN  Khong co du lieu
446   FUCVREIT       True        0         NaN  Khong co du lieu
...        ...        ...      ...         ...               ...
2044       VFW       True        0         NaN  Khong co du lieu
2045       VHW       True        0         NaN  Khong co du lieu
2046       VLD       True        0         NaN  Khong co du lieu
2047       VTT       True        0         NaN  Khong co du lieu
2048       YAN       True        0         NaN  Khong co du lieu

[116 rows x 5 columns]

In [6]:
log['CompanyType'].value_counts(dropna=False)

CompanyType
General       1848
NaN            116
Securities      42
Bank            31
Insurance       12
Name: count, dtype: int64

## Kiểm tra dữ liệu đã lưu

In [7]:
rows = []
with sqlite3.connect('fscore.db') as conn:
    tables = [r[0] for r in conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table' "
        "AND name LIKE 'fireant_financial_data_%' ORDER BY name")]
    for t in tables:
        n_sym, n_row, y0, y1 = conn.execute(
            f'SELECT COUNT(DISTINCT symbol), COUNT(*), MIN(Year), MAX(Year) '
            f'FROM "{t}"').fetchone()
        n_col = len(list(conn.execute(f'PRAGMA table_info("{t}")')))
        rows.append({'table': t, 'symbols': n_sym, 'rows': n_row,
                     'from': y0, 'to': y1, 'columns': n_col})

pd.DataFrame(rows)

                               table  symbols   rows  from    to  columns
0        fireant_financial_data_bank       31    456  2009  2025      300
1     fireant_financial_data_general     1848  23671  2009  2025      342
2   fireant_financial_data_insurance       12    176  2009  2025      421
3  fireant_financial_data_securities       42    457  2014  2025      451

In [8]:
# đọc lại một mã (bảng rộng, giữ nguyên tên trường API)
hpg_db = Fireant.load_financial_data('fscore.db', symbol='HPG', company_type='General')
hpg_db[['symbol', 'period', 'NetSale', 'ProfitAfterTax', 'StockHolderEquity',
        'ROE', 'ROA', 'PE', 'BasicEPS', 'CashDividend', 'PiotroskiFScore']]

,symbol,period,NetSale,ProfitAfterTax,StockHolderEquity,ROE,ROA,PE,BasicEPS,CashDividend,PiotroskiFScore
0,HPG,2009,8123394614746,1270706623417,5064948541660,0.27149,0.16016,9.03169,6477.19354,2000,4
1,HPG,2010,14267083816361,1376316086778,6737989072718,0.22864,0.10731,9.11633,5103.98977,2000,3
2,HPG,2011,17851896561575,1296850503678,7963631176519,0.16820,0.07626,4.43882,3917.58057,0,4
3,HPG,2012,16826851892984,1030505429517,8577557545150,0.12019,0.05441,8.85301,2780.62225,1000,4
4,HPG,2013,18934292150531,2010435402769,9586960019559,0.21517,0.09285,8.81341,4663.34739,1000,8
5,HPG,2014,25525348822713,3250214590204,11965339743609,0.29178,0.13923,8.12312,6799.13785,1500,7
6,HPG,2015,27452932114333,3504382487779,14466710385310,0.26373,0.14646,6.13982,5383.28030,1000,7
7,HPG,2016,33283210159987,6606202726929,19850261077964,0.38477,0.22482,5.50815,8556.36677,1500,7
8,HPG,2017,46161691614304,8014756586048,32397580211910,0.30649,0.18566,8.87600,6157.22569,0,4
9,HPG,2018,55836458379759,8600550706227,40622949840810,0.23481,0.13064,7.66766,4622.81549,0,2
10,HPG,2019,63658192673791,7578248236229,47786636143695,0.17029,0.08364,8.61983,3020.34986,0,4
11,HPG,2020,90118503426717,13506164056907,59219786306111,0.25139,0.11531,10.21059,4488.75748,500,6
12,HPG,2021,149679789979345,34520954931298,90780625511439,0.45971,0.22262,6.01957,8627.39038,500,7
13,HPG,2022,141409274460632,8444429054516,96112939615783,0.09078,0.04868,12.33760,1631.18165,500,5
14,HPG,2023,118953027893654,6800388315081,102836419239379,0.06871,0.03817,23.77787,1175.46281,0,4
15,HPG,2024,138855112131387,12020023621271,114647457983699,0.11055,0.05832,14.17967,1948.66514,0,5
16,HPG,2025,156116094618482,15514931571606,131220010876575,0.12570,0.06407,13.11267,2189.25701,0,6

In [9]:
# gộp mọi loại hình: các trường không dùng cho loại hình đó sẽ là NaN
allfd = Fireant.load_financial_data('fscore.db')
print(allfd.shape, '|', allfd['symbol'].nunique(), 'mã')
allfd.groupby('CompanyType')['symbol'].nunique()

(24760, 873) | 1933 mã

CompanyType
Bank            31
General       1848
Insurance       12
Securities      42
Name: symbol, dtype: int64

In [10]:
# độ phủ theo năm của từng loại hình
allfd.pivot_table(index='Year', columns='CompanyType', values='symbol',
                  aggfunc='nunique')

CompanyType  Bank  General  Insurance  Securities
Year
2009         11.0    924.0        8.0         NaN
2010         22.0    981.0        8.0         NaN
2011         26.0   1054.0        8.0         NaN
2012         26.0   1110.0        8.0         NaN
2013         26.0   1203.0        8.0         NaN
2014         27.0   1331.0        8.0        24.0
2015         28.0   1464.0       10.0        27.0
2016         29.0   1577.0       11.0        37.0
2017         29.0   1609.0       12.0        37.0
2018         29.0   1647.0       12.0        40.0
2019         29.0   1649.0       12.0        40.0
2020         29.0   1631.0       12.0        42.0
2021         29.0   1585.0       11.0        42.0
2022         29.0   1527.0       12.0        42.0
2023         29.0   1488.0       12.0        42.0
2024         29.0   1469.0       12.0        42.0
2025         29.0   1422.0       12.0        42.0

## Cập nhật / lấy thêm theo quý

* Cập nhật số liệu năm mới: chạy lại với `skip_existing=False` — `INSERT OR REPLACE` theo
  `(symbol, period)` nên ghi đè chứ không nhân dòng.
* Dữ liệu quý ghi vào **cùng bảng** với `period` dạng `'Q1-2026'`, không đụng khoá của bản năm.

In [11]:
# # cập nhật lại toàn bộ (ghi đè các kỳ đã có)
# log_update = fa.crawl_financial_data_to_db(
#     symbols, start_year=2009, db_path='fscore.db', skip_existing=False,
#     log_path='./logs/fireant_financial_data_update.csv', sleep=0.3)
# log_update

In [12]:
# # bản theo quý
# log_q = fa.crawl_financial_data_to_db(
#     symbols, start_year=2009, type_time='QUY', db_path='fscore.db',
#     skip_existing=False, log_path='./logs/fireant_financial_data_quy.csv', sleep=0.3)
# log_q