In [1]:
from vietstock_connector import Vietstock

vs = Vietstock(
    cookie_login='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidGF0YW4ucGhhdHR0QGdtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2hhc2giOiJzay16c0xDTXk2ZWh3R2VKbVZBclUyOE1BIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiJ0YXRhbi5waGF0dHRAZ21haWwuY29tIiwiZXhwIjoxNzg3NDc2NTE0LCJpc3MiOiIudmlldHN0b2NrLnZuIiwiYXVkIjoiLnZpZXRzdG9jay52biJ9.dGrVoFJVgp8OArQOTvPP3hNPWRZK0wy_KMB4hlfboQk',       # F12 > Application > Cookies
    usr_lg_token='XPaWPx5PFEOTvxehHuIg9w==',
)
listed   = vs.get_tickers(type=1)   # đang niêm yết
delisted = vs.get_tickers(type=4)   # đã huỷ niêm yết

type=1 page=1: +50 mã (tổng 50/1552)
type=1 page=2: +50 mã (tổng 100/1552)
type=1 page=3: +50 mã (tổng 150/1552)
type=1 page=4: +50 mã (tổng 200/1552)
type=1 page=5: +50 mã (tổng 250/1552)
type=1 page=6: +50 mã (tổng 300/1552)
type=1 page=7: +50 mã (tổng 350/1552)
type=1 page=8: +50 mã (tổng 400/1552)
type=1 page=9: +50 mã (tổng 450/1552)
type=1 page=10: +50 mã (tổng 500/1552)
type=1 page=11: +50 mã (tổng 550/1552)
type=1 page=12: +50 mã (tổng 600/1552)
type=1 page=13: +50 mã (tổng 650/1552)
type=1 page=14: +50 mã (tổng 700/1552)
type=1 page=15: +50 mã (tổng 750/1552)
type=1 page=16: +50 mã (tổng 800/1552)
type=1 page=17: +50 mã (tổng 850/1552)
type=1 page=18: +50 mã (tổng 900/1552)
type=1 page=19: +50 mã (tổng 950/1552)
type=1 page=20: +50 mã (tổng 1000/1552)
type=1 page=21: +50 mã (tổng 1050/1552)
type=1 page=22: +50 mã (tổng 1100/1552)
type=1 page=23: +50 mã (tổng 1150/1552)
type=1 page=24: +50 mã (tổng 1200/1552)
type=1 page=25: +50 mã (tổng 1250/1552)
type=1 page=26: +50 mã (tổng 1300/1552)
type=1 page=27: +50 mã (tổng 1350/1552)
type=1 page=28: +50 mã (tổng 1400/1552)
type=1 page=29: +50 mã (tổng 1450/1552)
type=1 page=30: +50 mã (tổng 1500/1552)
type=1 page=31: +50 mã (tổng 1550/1552)
type=1 page=32: +2 mã (tổng 1552/1552)
type=4 page=1: +47 mã (tổng 47/732)
type=4 page=2: +50 mã (tổng 97/732)
type=4 page=3: +49 mã (tổng 146/732)
type=4 page=4: +48 mã (tổng 194/732)
type=4 page=5: +48 mã (tổng 242/732)
type=4 page=6: +49 mã (tổng 291/732)
type=4 page=7: +49 mã (tổng 340/732)
type=4 page=8: +49 mã (tổng 389/732)
type=4 page=9: +50 mã (tổng 439/732)
type=4 page=10: +48 mã (tổng 487/732)
type=4 page=11: +50 mã (tổng 537/732)
type=4 page=12: +49 mã (tổng 586/732)
type=4 page=13: +49 mã (tổng 635/732)
type=4 page=14: +48 mã (tổng 683/732)
type=4 page=15: +30 mã (tổng 713/732)

In [8]:
listed["Exchange"] = listed["Exchange"].str.upper()

In [10]:
listed

,ID,CatID,Exchange,IndustryName1,IndustryName2,IndustryName3,Code,Name,TotalShares,URL,FirstTradeDate
0,4712,5,UPCOM,Tiêu dùng không thiết yếu,Thời trang và hàng lâu bền,Thời trang và dệt may,A32,CTCP 32,6800000,https://finance.vietstock.vn/A32-ctcp-32.htm,2018-10-22 17:00:00
1,2541,1,HOSE,Nguyên vật liệu,Nguyên vật liệu,Hóa chất,AAA,CTCP Nhựa An Phát Xanh,393742730,https://finance.vietstock.vn/AAA-ctcp-nhua-an-...,2016-11-24 17:00:00
2,5601,5,UPCOM,Năng lượng,Năng lượng,Dầu khí,AAH,CTCP Hợp Nhất,117900000,https://finance.vietstock.vn/AAH-ctcp-hop-nhat...,2024-01-10 17:00:00
3,1813,1,HOSE,Tiêu dùng thiết yếu,"Thực phẩm, đồ uống và thuốc lá",Thực phẩm,AAM,CTCP Thủy sản MeKong,12346411,https://finance.vietstock.vn/AAM-ctcp-thuy-san...,2009-09-23 17:00:00
4,5816,1,HOSE,Tiêu dùng thiết yếu,"Thực phẩm, đồ uống và thuốc lá",Thực phẩm,AAN,CTCP Lương thực A An,91649951,https://finance.vietstock.vn/AAN-ctcp-luong-th...,2026-05-21 17:00:00
...,...,...,...,...,...,...,...,...,...,...,...
1547,2298,5,UPCOM,Tiêu dùng thiết yếu,Sản phẩm chăm sóc cá nhân và gia đình,Sản phẩm chăm sóc gia đình,XPH,CTCP Xà phòng Hà Nội,12972475,https://finance.vietstock.vn/XPH-ctcp-xa-phong...,2014-11-24 17:00:00
1548,1138,5,UPCOM,Nguyên vật liệu,Nguyên vật liệu,Vật liệu xây dựng,YBC,CTCP Xi măng và Khoáng sản Yên Bái,11800000,https://finance.vietstock.vn/YBC-ctcp-xi-mang-...,2014-06-24 17:00:00
1549,4687,1,HOSE,Nguyên vật liệu,Nguyên vật liệu,Vật liệu xây dựng,YBM,CTCP YBM,32174525,https://finance.vietstock.vn/YBM-ctcp-ybm.htm,2018-08-20 17:00:00
1550,4680,1,HOSE,Dịch vụ truyền thông,Truyền thông và giải trí,Truyền thông,YEG,CTCP Tập đoàn Yeah1,205226448,https://finance.vietstock.vn/YEG-ctcp-tap-doan...,2018-06-25 17:00:00
1551,2008,5,UPCOM,Chăm sóc sức khỏe,Thiết bị và dịch vụ chăm sóc sức khỏe,Thương mại và dịch vụ chăm sóc sức khỏe,YTC,CTCP Xuất nhập khẩu Y tế Thành phố Hồ Chí Minh,9548000,https://finance.vietstock.vn/YTC-ctcp-xuat-nha...,2017-08-02 17:00:00

In [5]:
delisted

,ID,Code,Name,CatID,Exchange,BeforeExchange,URL,CancelVolume,IndustryName,Title,FileUrl,NDKCCDate
0,2541,AAA,CTCP Nhựa An Phát Xanh,1,HOSE,HNX,https://finance.vietstock.vn/AAA-ctcp-nhua-an-...,51899988,Nguyên vật liệu,"AAA: Ngày 18/11/2016, ngày hủy niêm yết cổ phi...",http://static2.vietstock.vn/vietstock/2016/11/...,2016-11-16 17:00:00
1,4522,AAV,CTCP AAV Group,5,UPCOM,HNX,https://finance.vietstock.vn/AAV-ctcp-aav-grou...,68987661,Bất động sản,"AAV: Ngày 15/05/2026, về việc hủy bỏ niêm ...",https://static2.vietstock.vn/vietstock/2026/4/...,2026-05-13 17:00:00
2,4473,ABR,CTCP Đầu tư Nhãn hiệu Việt,1,HOSE,UPCOM,https://finance.vietstock.vn/ABR-ctcp-dau-tu-n...,20000000,Dịch vụ viễn thông,"ABR: Ngày 22/02/2022, ngày hủy ĐKGD cổ phiếu c...",http://static2.vietstock.vn/vietstock/2022/2/1...,2022-02-20 17:00:00
3,2995,AC4,CTCP ACC-244,3,OTC,UPCOM,https://finance.vietstock.vn/AC4-ctcp-acc-244.htm,2940862,Hàng hóa công nghiệp,"AC4: Ngày 09/06/2021, ngày hủy ĐKGD cổ phiếu c...",http://static2.vietstock.vn/vietstock/2021/5/1...,2021-06-07 17:00:00
4,885,ACB,Ngân hàng TMCP Á Châu,1,HOSE,HNX,https://finance.vietstock.vn/ACB-ngan-hang-tmc...,2161558460,Tổ chức tín dụng,"ACB: Ngày 02/12/2020, ngày hủy niêm yết cổ phi...",http://static2.vietstock.vn/vietstock/2020/11/...,2020-11-30 17:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...
708,2350,X18,CTCP Xi măng X18,3,OTC,UPCOM,https://finance.vietstock.vn/X18-ctcp-xi-mang-...,4155777,Nguyên vật liệu,"X18: Ngày 17/07/2020, ngày hủy ĐKGD cổ phiếu c...",https://owa.hnx.vn/ftp///cims/2020/7_W3/000000...,2020-07-15 17:00:00
709,4922,XDC,CTCP Xây Dựng Công Trình Tân Cảng,3,OTC,UPCOM,https://finance.vietstock.vn/XDC-ctcp-xay-dung...,8200,Hàng hóa công nghiệp,"XDC: Ngày 29/12/2023, ngày hủy ĐKGD cổ phiếu c...",https://static2.vietstock.vn/vietstock/2023/12...,2023-12-27 17:00:00
710,1073,XMC,CTCP Đầu tư và Xây dựng Xuân Mai,5,UPCOM,HNX,https://finance.vietstock.vn/XMC-ctcp-dau-tu-v...,19998240,Hàng hóa công nghiệp,XMC: Thông báo về việc hủy niêm yết cổ phiếu XMC,HTTP://STATIC2.VIETSTOCK.VN/VIETSTOCK/2013/11/...,2013-11-10 17:00:00
711,1138,YBC,CTCP Xi măng và Khoáng sản Yên Bái,5,UPCOM,HNX,https://finance.vietstock.vn/YBC-ctcp-xi-mang-...,4837430,Nguyên vật liệu,"YBC: Ngày 28/05/2014, ngày hủy niêm yết cổ phi...",http://static2.vietstock.vn/vietstock/2014/5/5...,2014-05-26 17:00:00
712,4377,YRC,CTCP Đường sắt Yên Lào,3,OTC,UPCOM,https://finance.vietstock.vn/YRC-ctcp-duong-sa...,1900000,Vận tải,"YRC: Ngày 13/08/2021, ngày hủy ĐKGD cổ phiếu c...",http://static2.vietstock.vn/vietstock/2021/7/2...,2021-08-11 17:00:00

In [11]:
merged = listed.merge(delisted, how='outer', on=['Code', "Exchange"])

In [14]:
len(merged)

1964

In [13]:
merged[merged["Exchange"] == "OTC"]

,ID_x,CatID_x,Exchange,IndustryName1,IndustryName2,IndustryName3,Code,Name_x,TotalShares,URL_x,...,ID_y,Name_y,CatID_y,BeforeExchange,URL_y,CancelVolume,IndustryName,Title,FileUrl,NDKCCDate
15,NaN,NaN,OTC,NaN,NaN,NaN,AC4,NaN,NaN,NaN,...,2995.0,CTCP ACC-244,3.0,UPCOM,https://finance.vietstock.vn/AC4-ctcp-acc-244.htm,2940862.0,Hàng hóa công nghiệp,"AC4: Ngày 09/06/2021, ngày hủy ĐKGD cổ phiếu c...",http://static2.vietstock.vn/vietstock/2021/5/1...,2021-06-07 17:00:00
28,NaN,NaN,OTC,NaN,NaN,NaN,AFC,NaN,NaN,NaN,...,4511.0,CTCP Nông Lâm nghiệp Bình Dương,3.0,UPCOM,https://finance.vietstock.vn/AFC-ctcp-nong-lam...,10688363.0,Dịch vụ thương mại và chuyên nghiệp,"AFC: Ngày 27/05/2020, ngày hủy ĐKGD cổ phiếu c...",https://owa.hnx.vn/ftp///cims/2020/5_W2/000000...,2020-05-25 17:00:00
31,NaN,NaN,OTC,NaN,NaN,NaN,AGD,NaN,NaN,NaN,...,1882.0,CTCP Gò Đàng,3.0,HOSE,https://finance.vietstock.vn/AGD-ctcp-go-dang.htm,11999930.0,"Thực phẩm, đồ uống và thuốc lá",AGD: Quyết định hủy niêm yết cổ phiếu,,2013-08-26 17:00:00
32,NaN,NaN,OTC,NaN,NaN,NaN,AGE,NaN,NaN,NaN,...,4664.0,CTCP Môi trường Đô thị An Giang,3.0,UPCOM,https://finance.vietstock.vn/AGE-ctcp-moi-truo...,19893000.0,Dịch vụ thương mại và chuyên nghiệp,"AGE: Ngày 22/09/2023, ngày hủy ĐKGD cổ phiếu c...",https://static2.vietstock.vn/vietstock/2023/9/...,2023-09-20 17:00:00
42,NaN,NaN,OTC,NaN,NaN,NaN,ALP,NaN,NaN,NaN,...,1064.0,CTCP Đầu tư Alphanam,3.0,HOSE,https://finance.vietstock.vn/ALP-ctcp-dau-tu-a...,192484413.0,Hàng hóa công nghiệp,ALP: Quyết định hủy niêm yết cổ phiếu,,2014-12-29 17:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1924,NaN,NaN,OTC,NaN,NaN,NaN,VTL,NaN,NaN,NaN,...,1108.0,CTCP Vang Thăng Long,3.0,HNX,https://finance.vietstock.vn/VTL-ctcp-vang-tha...,5059992.0,"Thực phẩm, đồ uống và thuốc lá","VTL: Ngày 19/05/2023, ngày hủy niêm yết cổ phi...",https://static2.vietstock.vn/vietstock/2023/4/...,2023-05-17 17:00:00
1946,NaN,NaN,OTC,NaN,NaN,NaN,WTN,NaN,NaN,NaN,...,4200.0,CTCP Cấp thoát nước Tây Ninh,3.0,UPCOM,https://finance.vietstock.vn/WTN-ctcp-cap-thoa...,10576827.0,Tiện ích,"WTN: Ngày 04/09/2020, ngày hủy ĐKGD cổ phiếu c...",https://owa.hnx.vn/ftp///cims/2020/8_W3/000000...,2020-09-02 17:00:00
1947,NaN,NaN,OTC,NaN,NaN,NaN,X18,NaN,NaN,NaN,...,2350.0,CTCP Xi măng X18,3.0,UPCOM,https://finance.vietstock.vn/X18-ctcp-xi-mang-...,4155777.0,Nguyên vật liệu,"X18: Ngày 17/07/2020, ngày hủy ĐKGD cổ phiếu c...",https://owa.hnx.vn/ftp///cims/2020/7_W3/000000...,2020-07-15 17:00:00
1951,NaN,NaN,OTC,NaN,NaN,NaN,XDC,NaN,NaN,NaN,...,4922.0,CTCP Xây Dựng Công Trình Tân Cảng,3.0,UPCOM,https://finance.vietstock.vn/XDC-ctcp-xay-dung...,8200.0,Hàng hóa công nghiệp,"XDC: Ngày 29/12/2023, ngày hủy ĐKGD cổ phiếu c...",https://static2.vietstock.vn/vietstock/2023/12...,2023-12-27 17:00:00
1962,NaN,NaN,OTC,NaN,NaN,NaN,YRC,NaN,NaN,NaN,...,4377.0,CTCP Đường sắt Yên Lào,3.0,UPCOM,https://finance.vietstock.vn/YRC-ctcp-duong-sa...,1900000.0,Vận tải,"YRC: Ngày 13/08/2021, ngày hủy ĐKGD cổ phiếu c...",http://static2.vietstock.vn/vietstock/2021/7/2...,2021-08-11 17:00:00

In [38]:
merged[~merged["ID_x"].isnull()]

,ID_x,CatID_x,Exchange,IndustryName1,IndustryName2,IndustryName3,Code,Name_x,TotalShares,URL_x,...,ID_y,Name_y,CatID_y,BeforeExchange,URL_y,CancelVolume,IndustryName,Title,FileUrl,NDKCCDate
0,4712.0,5.0,UPCOM,Tiêu dùng không thiết yếu,Thời trang và hàng lâu bền,Thời trang và dệt may,A32,CTCP 32,6800000.0,https://finance.vietstock.vn/A32-ctcp-32.htm,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
1,2541.0,1.0,HOSE,Nguyên vật liệu,Nguyên vật liệu,Hóa chất,AAA,CTCP Nhựa An Phát Xanh,393742730.0,https://finance.vietstock.vn/AAA-ctcp-nhua-an-...,...,2541.0,CTCP Nhựa An Phát Xanh,1.0,HNX,https://finance.vietstock.vn/AAA-ctcp-nhua-an-...,51899988.0,Nguyên vật liệu,"AAA: Ngày 18/11/2016, ngày hủy niêm yết cổ phi...",http://static2.vietstock.vn/vietstock/2016/11/...,2016-11-16 17:00:00
2,5601.0,5.0,UPCOM,Năng lượng,Năng lượng,Dầu khí,AAH,CTCP Hợp Nhất,117900000.0,https://finance.vietstock.vn/AAH-ctcp-hop-nhat...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
3,1813.0,1.0,HOSE,Tiêu dùng thiết yếu,"Thực phẩm, đồ uống và thuốc lá",Thực phẩm,AAM,CTCP Thủy sản MeKong,12346411.0,https://finance.vietstock.vn/AAM-ctcp-thuy-san...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
4,5816.0,1.0,HOSE,Tiêu dùng thiết yếu,"Thực phẩm, đồ uống và thuốc lá",Thực phẩm,AAN,CTCP Lương thực A An,91649951.0,https://finance.vietstock.vn/AAN-ctcp-luong-th...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1958,2298.0,5.0,UPCOM,Tiêu dùng thiết yếu,Sản phẩm chăm sóc cá nhân và gia đình,Sản phẩm chăm sóc gia đình,XPH,CTCP Xà phòng Hà Nội,12972475.0,https://finance.vietstock.vn/XPH-ctcp-xa-phong...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
1959,1138.0,5.0,UPCOM,Nguyên vật liệu,Nguyên vật liệu,Vật liệu xây dựng,YBC,CTCP Xi măng và Khoáng sản Yên Bái,11800000.0,https://finance.vietstock.vn/YBC-ctcp-xi-mang-...,...,1138.0,CTCP Xi măng và Khoáng sản Yên Bái,5.0,HNX,https://finance.vietstock.vn/YBC-ctcp-xi-mang-...,4837430.0,Nguyên vật liệu,"YBC: Ngày 28/05/2014, ngày hủy niêm yết cổ phi...",http://static2.vietstock.vn/vietstock/2014/5/5...,2014-05-26 17:00:00
1960,4687.0,1.0,HOSE,Nguyên vật liệu,Nguyên vật liệu,Vật liệu xây dựng,YBM,CTCP YBM,32174525.0,https://finance.vietstock.vn/YBM-ctcp-ybm.htm,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
1961,4680.0,1.0,HOSE,Dịch vụ truyền thông,Truyền thông và giải trí,Truyền thông,YEG,CTCP Tập đoàn Yeah1,205226448.0,https://finance.vietstock.vn/YEG-ctcp-tap-doan...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
1963,2008.0,5.0,UPCOM,Chăm sóc sức khỏe,Thiết bị và dịch vụ chăm sóc sức khỏe,Thương mại và dịch vụ chăm sóc sức khỏe,YTC,CTCP Xuất nhập khẩu Y tế Thành phố Hồ Chí Minh,9548000.0,https://finance.vietstock.vn/YTC-ctcp-xuat-nha...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT

In [50]:
import pandas as pd
df_listed_temp = merged[~merged["ID_x"].isnull()]
listed_normalized = pd.DataFrame({
    "ID": df_listed_temp["ID_x"],
    "Symbol": df_listed_temp["Code"],
    "CompanyName": df_listed_temp["Name_x"],
    "Exchange": df_listed_temp["Exchange"],
    "IndustryName1": df_listed_temp["IndustryName1"],
    "IndustryName2": df_listed_temp["IndustryName2"],
    "IndustryName3": df_listed_temp["IndustryName3"],
    "FirstTradeDate": df_listed_temp["FirstTradeDate"],
    "BeforeExchange": df_listed_temp["BeforeExchange"],
    "DelistedReason": df_listed_temp["Title"]
})
listed_normalized["IsTerminated"] = False
listed_normalized

,ID,Symbol,CompanyName,Exchange,IndustryName1,IndustryName2,IndustryName3,FirstTradeDate,BeforeExchange,DelistedReason,IsTerminated
0,4712.0,A32,CTCP 32,UPCOM,Tiêu dùng không thiết yếu,Thời trang và hàng lâu bền,Thời trang và dệt may,2018-10-22 17:00:00,NaN,NaN,False
1,2541.0,AAA,CTCP Nhựa An Phát Xanh,HOSE,Nguyên vật liệu,Nguyên vật liệu,Hóa chất,2016-11-24 17:00:00,HNX,"AAA: Ngày 18/11/2016, ngày hủy niêm yết cổ phi...",False
2,5601.0,AAH,CTCP Hợp Nhất,UPCOM,Năng lượng,Năng lượng,Dầu khí,2024-01-10 17:00:00,NaN,NaN,False
3,1813.0,AAM,CTCP Thủy sản MeKong,HOSE,Tiêu dùng thiết yếu,"Thực phẩm, đồ uống và thuốc lá",Thực phẩm,2009-09-23 17:00:00,NaN,NaN,False
4,5816.0,AAN,CTCP Lương thực A An,HOSE,Tiêu dùng thiết yếu,"Thực phẩm, đồ uống và thuốc lá",Thực phẩm,2026-05-21 17:00:00,NaN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...
1958,2298.0,XPH,CTCP Xà phòng Hà Nội,UPCOM,Tiêu dùng thiết yếu,Sản phẩm chăm sóc cá nhân và gia đình,Sản phẩm chăm sóc gia đình,2014-11-24 17:00:00,NaN,NaN,False
1959,1138.0,YBC,CTCP Xi măng và Khoáng sản Yên Bái,UPCOM,Nguyên vật liệu,Nguyên vật liệu,Vật liệu xây dựng,2014-06-24 17:00:00,HNX,"YBC: Ngày 28/05/2014, ngày hủy niêm yết cổ phi...",False
1960,4687.0,YBM,CTCP YBM,HOSE,Nguyên vật liệu,Nguyên vật liệu,Vật liệu xây dựng,2018-08-20 17:00:00,NaN,NaN,False
1961,4680.0,YEG,CTCP Tập đoàn Yeah1,HOSE,Dịch vụ truyền thông,Truyền thông và giải trí,Truyền thông,2018-06-25 17:00:00,NaN,NaN,False
1963,2008.0,YTC,CTCP Xuất nhập khẩu Y tế Thành phố Hồ Chí Minh,UPCOM,Chăm sóc sức khỏe,Thiết bị và dịch vụ chăm sóc sức khỏe,Thương mại và dịch vụ chăm sóc sức khỏe,2017-08-02 17:00:00,NaN,NaN,False

In [54]:
import numpy as np
terminated = delisted[(delisted["Exchange"] == "OTC") | (delisted["Exchange"] == "Khác")]
terminated

terminated_normalized = pd.DataFrame({
    "ID": terminated["ID"],
    "Symbol": terminated["Code"],
    "CompanyName": terminated["Name"],
    "Exchange": terminated["Exchange"],
    "IndustryName2": terminated["IndustryName"],
    "BeforeExchange": terminated["BeforeExchange"],
    "DelistedReason": terminated["Title"]
})
terminated_normalized['IndustryName1'] = np.nan
terminated_normalized['IndustryName3'] = np.nan
terminated_normalized['FirstTradeDate'] = np.nan
terminated_normalized["IsTerminated"] = True
terminated_normalized

,ID,Symbol,CompanyName,Exchange,IndustryName2,BeforeExchange,DelistedReason,IndustryName1,IndustryName3,FirstTradeDate,IsTerminated
3,2995,AC4,CTCP ACC-244,OTC,Hàng hóa công nghiệp,UPCOM,"AC4: Ngày 09/06/2021, ngày hủy ĐKGD cổ phiếu c...",NaN,NaN,NaN,True
9,4511,AFC,CTCP Nông Lâm nghiệp Bình Dương,OTC,Dịch vụ thương mại và chuyên nghiệp,UPCOM,"AFC: Ngày 27/05/2020, ngày hủy ĐKGD cổ phiếu c...",NaN,NaN,NaN,True
11,1882,AGD,CTCP Gò Đàng,OTC,"Thực phẩm, đồ uống và thuốc lá",HOSE,AGD: Quyết định hủy niêm yết cổ phiếu,NaN,NaN,NaN,True
12,4664,AGE,CTCP Môi trường Đô thị An Giang,OTC,Dịch vụ thương mại và chuyên nghiệp,UPCOM,"AGE: Ngày 22/09/2023, ngày hủy ĐKGD cổ phiếu c...",NaN,NaN,NaN,True
15,1064,ALP,CTCP Đầu tư Alphanam,OTC,Hàng hóa công nghiệp,HOSE,ALP: Quyết định hủy niêm yết cổ phiếu,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...
702,1108,VTL,CTCP Vang Thăng Long,OTC,"Thực phẩm, đồ uống và thuốc lá",HNX,"VTL: Ngày 19/05/2023, ngày hủy niêm yết cổ phi...",NaN,NaN,NaN,True
707,4200,WTN,CTCP Cấp thoát nước Tây Ninh,OTC,Tiện ích,UPCOM,"WTN: Ngày 04/09/2020, ngày hủy ĐKGD cổ phiếu c...",NaN,NaN,NaN,True
708,2350,X18,CTCP Xi măng X18,OTC,Nguyên vật liệu,UPCOM,"X18: Ngày 17/07/2020, ngày hủy ĐKGD cổ phiếu c...",NaN,NaN,NaN,True
709,4922,XDC,CTCP Xây Dựng Công Trình Tân Cảng,OTC,Hàng hóa công nghiệp,UPCOM,"XDC: Ngày 29/12/2023, ngày hủy ĐKGD cổ phiếu c...",NaN,NaN,NaN,True
712,4377,YRC,CTCP Đường sắt Yên Lào,OTC,Vận tải,UPCOM,"YRC: Ngày 13/08/2021, ngày hủy ĐKGD cổ phiếu c...",NaN,NaN,NaN,True

In [55]:
final = pd.concat([listed_normalized, terminated_normalized], ignore_index=True)
final

,ID,Symbol,CompanyName,Exchange,IndustryName1,IndustryName2,IndustryName3,FirstTradeDate,BeforeExchange,DelistedReason,IsTerminated
0,4712.0,A32,CTCP 32,UPCOM,Tiêu dùng không thiết yếu,Thời trang và hàng lâu bền,Thời trang và dệt may,2018-10-22 17:00:00,NaN,NaN,False
1,2541.0,AAA,CTCP Nhựa An Phát Xanh,HOSE,Nguyên vật liệu,Nguyên vật liệu,Hóa chất,2016-11-24 17:00:00,HNX,"AAA: Ngày 18/11/2016, ngày hủy niêm yết cổ phi...",False
2,5601.0,AAH,CTCP Hợp Nhất,UPCOM,Năng lượng,Năng lượng,Dầu khí,2024-01-10 17:00:00,NaN,NaN,False
3,1813.0,AAM,CTCP Thủy sản MeKong,HOSE,Tiêu dùng thiết yếu,"Thực phẩm, đồ uống và thuốc lá",Thực phẩm,2009-09-23 17:00:00,NaN,NaN,False
4,5816.0,AAN,CTCP Lương thực A An,HOSE,Tiêu dùng thiết yếu,"Thực phẩm, đồ uống và thuốc lá",Thực phẩm,2026-05-21 17:00:00,NaN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...
1959,1108.0,VTL,CTCP Vang Thăng Long,OTC,NaN,"Thực phẩm, đồ uống và thuốc lá",NaN,NaN,HNX,"VTL: Ngày 19/05/2023, ngày hủy niêm yết cổ phi...",True
1960,4200.0,WTN,CTCP Cấp thoát nước Tây Ninh,OTC,NaN,Tiện ích,NaN,NaN,UPCOM,"WTN: Ngày 04/09/2020, ngày hủy ĐKGD cổ phiếu c...",True
1961,2350.0,X18,CTCP Xi măng X18,OTC,NaN,Nguyên vật liệu,NaN,NaN,UPCOM,"X18: Ngày 17/07/2020, ngày hủy ĐKGD cổ phiếu c...",True
1962,4922.0,XDC,CTCP Xây Dựng Công Trình Tân Cảng,OTC,NaN,Hàng hóa công nghiệp,NaN,NaN,UPCOM,"XDC: Ngày 29/12/2023, ngày hủy ĐKGD cổ phiếu c...",True
1963,4377.0,YRC,CTCP Đường sắt Yên Lào,OTC,NaN,Vận tải,NaN,NaN,UPCOM,"YRC: Ngày 13/08/2021, ngày hủy ĐKGD cổ phiếu c...",True

In [17]:
merged["Code"]

0       A32
1       AAA
2       AAH
3       AAM
4       AAN
       ...
1959    YBC
1960    YBM
1961    YEG
1962    YRC
1963    YTC
Name: Code, Length: 1964, dtype: str

In [18]:
import pandas as pd
cafef_tickers = pd.read_json('./data/ticker.json')

In [48]:
cafef_tickers

,Symbol,TradeCenterId,CategoryId,CompanyName,CategoryName,Price,TotalCompany
0,24H,8,429,CTCP Quảng cáo trực tuyến 24H,Phần mềm và dịch vụ,0.00,1640
1,A32,9,339,Công ty cổ phần 32,Hàng tiêu dùng,31.00,1640
2,AAA,1,344,Công ty Cổ phần Nhựa An Phát Xanh,Nguyên vật liệu,7.20,1640
3,AAH,9,0,Công ty cổ phần Hợp Nhất,NaN,2.30,1640
4,AAM,1,338,Công ty Cổ phần Thủy sản Mekong,Nông nghiệp,6.60,1640
...,...,...,...,...,...,...,...
1635,YAN,8,346,CTCP Công nghệ và Tầm nhìn Yêu âm nhạc,Dịch vụ,0.00,1640
1636,YBC,9,345,Công ty Cổ phần Xi măng và Khoáng sản Yên Bái,Bất động sản và Xây dựng,7.30,1640
1637,YBM,1,344,Công ty Cổ phần YBM,Nguyên vật liệu,9.65,1640
1638,YEG,1,346,Công ty Cổ phần Tập đoàn Yeah1,Dịch vụ,8.30,1640
1639,YTC,9,342,Công ty Cổ phần Xuất nhập khẩu Y tế Thành phố ...,Y tế,21.70,1640

In [19]:
cafef_tickers['Symbol']

0       24H
1       A32
2       AAA
3       AAH
4       AAM
       ...
1635    YAN
1636    YBC
1637    YBM
1638    YEG
1639    YTC
Name: Symbol, Length: 1640, dtype: str

In [23]:
merged[~merged["Code"].isin(cafef_tickers['Symbol'])]

,ID_x,CatID_x,Exchange,IndustryName1,IndustryName2,IndustryName3,Code,Name_x,TotalShares,URL_x,...,ID_y,Name_y,CatID_y,BeforeExchange,URL_y,CancelVolume,IndustryName,Title,FileUrl,NDKCCDate
15,NaN,NaN,OTC,NaN,NaN,NaN,AC4,NaN,NaN,NaN,...,2995.0,CTCP ACC-244,3.0,UPCOM,https://finance.vietstock.vn/AC4-ctcp-acc-244.htm,2940862.0,Hàng hóa công nghiệp,"AC4: Ngày 09/06/2021, ngày hủy ĐKGD cổ phiếu c...",http://static2.vietstock.vn/vietstock/2021/5/1...,2021-06-07 17:00:00
28,NaN,NaN,OTC,NaN,NaN,NaN,AFC,NaN,NaN,NaN,...,4511.0,CTCP Nông Lâm nghiệp Bình Dương,3.0,UPCOM,https://finance.vietstock.vn/AFC-ctcp-nong-lam...,10688363.0,Dịch vụ thương mại và chuyên nghiệp,"AFC: Ngày 27/05/2020, ngày hủy ĐKGD cổ phiếu c...",https://owa.hnx.vn/ftp///cims/2020/5_W2/000000...,2020-05-25 17:00:00
31,NaN,NaN,OTC,NaN,NaN,NaN,AGD,NaN,NaN,NaN,...,1882.0,CTCP Gò Đàng,3.0,HOSE,https://finance.vietstock.vn/AGD-ctcp-go-dang.htm,11999930.0,"Thực phẩm, đồ uống và thuốc lá",AGD: Quyết định hủy niêm yết cổ phiếu,,2013-08-26 17:00:00
32,NaN,NaN,OTC,NaN,NaN,NaN,AGE,NaN,NaN,NaN,...,4664.0,CTCP Môi trường Đô thị An Giang,3.0,UPCOM,https://finance.vietstock.vn/AGE-ctcp-moi-truo...,19893000.0,Dịch vụ thương mại và chuyên nghiệp,"AGE: Ngày 22/09/2023, ngày hủy ĐKGD cổ phiếu c...",https://static2.vietstock.vn/vietstock/2023/9/...,2023-09-20 17:00:00
42,NaN,NaN,OTC,NaN,NaN,NaN,ALP,NaN,NaN,NaN,...,1064.0,CTCP Đầu tư Alphanam,3.0,HOSE,https://finance.vietstock.vn/ALP-ctcp-dau-tu-a...,192484413.0,Hàng hóa công nghiệp,ALP: Quyết định hủy niêm yết cổ phiếu,,2014-12-29 17:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1918,NaN,NaN,OTC,NaN,NaN,NaN,VTF,NaN,NaN,NaN,...,2219.0,CTCP Thức ăn Chăn nuôi Việt Thắng,3.0,HOSE,https://finance.vietstock.vn/VTF-ctcp-thuc-an-...,41812781.0,"Thực phẩm, đồ uống và thuốc lá",VTF: Quyết định hủy niêm yết cổ phiếu,https://www.hsx.vn/Modules/Cms/Web/DownloadFil...,2015-12-13 17:00:00
1946,NaN,NaN,OTC,NaN,NaN,NaN,WTN,NaN,NaN,NaN,...,4200.0,CTCP Cấp thoát nước Tây Ninh,3.0,UPCOM,https://finance.vietstock.vn/WTN-ctcp-cap-thoa...,10576827.0,Tiện ích,"WTN: Ngày 04/09/2020, ngày hủy ĐKGD cổ phiếu c...",https://owa.hnx.vn/ftp///cims/2020/8_W3/000000...,2020-09-02 17:00:00
1947,NaN,NaN,OTC,NaN,NaN,NaN,X18,NaN,NaN,NaN,...,2350.0,CTCP Xi măng X18,3.0,UPCOM,https://finance.vietstock.vn/X18-ctcp-xi-mang-...,4155777.0,Nguyên vật liệu,"X18: Ngày 17/07/2020, ngày hủy ĐKGD cổ phiếu c...",https://owa.hnx.vn/ftp///cims/2020/7_W3/000000...,2020-07-15 17:00:00
1951,NaN,NaN,OTC,NaN,NaN,NaN,XDC,NaN,NaN,NaN,...,4922.0,CTCP Xây Dựng Công Trình Tân Cảng,3.0,UPCOM,https://finance.vietstock.vn/XDC-ctcp-xay-dung...,8200.0,Hàng hóa công nghiệp,"XDC: Ngày 29/12/2023, ngày hủy ĐKGD cổ phiếu c...",https://static2.vietstock.vn/vietstock/2023/12...,2023-12-27 17:00:00
1962,NaN,NaN,OTC,NaN,NaN,NaN,YRC,NaN,NaN,NaN,...,4377.0,CTCP Đường sắt Yên Lào,3.0,UPCOM,https://finance.vietstock.vn/YRC-ctcp-duong-sa...,1900000.0,Vận tải,"YRC: Ngày 13/08/2021, ngày hủy ĐKGD cổ phiếu c...",http://static2.vietstock.vn/vietstock/2021/7/2...,2021-08-11 17:00:00

In [53]:
terminated_cafef = cafef_tickers[~cafef_tickers["Symbol"].isin(merged['Code'])]
terminated_cafef["Exchange"] = terminated_cafef["TradeCenterId"].map({
    8: "OTC",
    2: "HNX"
})
terminated_cafef
terminated_cafef_normalized = pd.DataFrame({
    "Symbol": terminated_cafef["Symbol"],
    "Exchange": terminated_cafef["Exchange"],
    "CompanyName": terminated_cafef["CompanyName"],
    "IndustryName2": terminated_cafef["CategoryName"],
})

terminated_cafef_normalized["IndustryName1"] = np.nan
terminated_cafef_normalized['IndustryName3'] = np.nan
terminated_cafef_normalized["BeforeExchange"] = np.nan
terminated_cafef_normalized["DelistedReason"] = np.nan
terminated_cafef_normalized['FirstTradeDate'] = np.nan
terminated_cafef_normalized["IsTerminated"] = True
terminated_cafef_normalized

,Symbol,Exchange,CompanyName,IndustryName2,IndustryName1,IndustryName3,BeforeExchange,DelistedReason,FirstTradeDate,IsTerminated
0,24H,OTC,CTCP Quảng cáo trực tuyến 24H,Phần mềm và dịch vụ,NaN,NaN,NaN,NaN,NaN,True
9,ABA,OTC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
12,ABF,OTC,Công ty cổ phần Quản lý quỹ đầu tư Chứng khoán...,Tài chính,NaN,NaN,NaN,NaN,NaN,True
30,AFM,OTC,Công ty Cổ phần Quản lý quỹ AIC,,NaN,NaN,NaN,NaN,NaN,True
63,ASC,OTC,Công ty Cổ phần Chứng khoán ASC,Tài chính,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...
1497,VFW,OTC,Công ty Cổ phần Quản lý quỹ Lộc Việt,,NaN,NaN,NaN,NaN,NaN,True
1515,VHW,OTC,CTCP Nước Khoáng Vĩnh Hảo,Hàng tiêu dùng,NaN,NaN,NaN,NaN,NaN,True
1536,VLD,OTC,Công ty Cổ phần Bất Động Sản Viettronics,,NaN,NaN,NaN,NaN,NaN,True
1609,VTT,HNX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1635,YAN,OTC,CTCP Công nghệ và Tầm nhìn Yêu âm nhạc,Dịch vụ,NaN,NaN,NaN,NaN,NaN,True

In [57]:
final = pd.concat([final, terminated_cafef_normalized], ignore_index=True)
final

,ID,Symbol,CompanyName,Exchange,IndustryName1,IndustryName2,IndustryName3,FirstTradeDate,BeforeExchange,DelistedReason,IsTerminated
0,4712.0,A32,CTCP 32,UPCOM,Tiêu dùng không thiết yếu,Thời trang và hàng lâu bền,Thời trang và dệt may,2018-10-22 17:00:00,NaN,NaN,False
1,2541.0,AAA,CTCP Nhựa An Phát Xanh,HOSE,Nguyên vật liệu,Nguyên vật liệu,Hóa chất,2016-11-24 17:00:00,HNX,"AAA: Ngày 18/11/2016, ngày hủy niêm yết cổ phi...",False
2,5601.0,AAH,CTCP Hợp Nhất,UPCOM,Năng lượng,Năng lượng,Dầu khí,2024-01-10 17:00:00,NaN,NaN,False
3,1813.0,AAM,CTCP Thủy sản MeKong,HOSE,Tiêu dùng thiết yếu,"Thực phẩm, đồ uống và thuốc lá",Thực phẩm,2009-09-23 17:00:00,NaN,NaN,False
4,5816.0,AAN,CTCP Lương thực A An,HOSE,Tiêu dùng thiết yếu,"Thực phẩm, đồ uống và thuốc lá",Thực phẩm,2026-05-21 17:00:00,NaN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...
2044,NaN,VFW,Công ty Cổ phần Quản lý quỹ Lộc Việt,OTC,NaN,,NaN,NaN,NaN,NaN,True
2045,NaN,VHW,CTCP Nước Khoáng Vĩnh Hảo,OTC,NaN,Hàng tiêu dùng,NaN,NaN,NaN,NaN,True
2046,NaN,VLD,Công ty Cổ phần Bất Động Sản Viettronics,OTC,NaN,,NaN,NaN,NaN,NaN,True
2047,NaN,VTT,NaN,HNX,NaN,NaN,NaN,NaN,NaN,NaN,True
2048,NaN,YAN,CTCP Công nghệ và Tầm nhìn Yêu âm nhạc,OTC,NaN,Dịch vụ,NaN,NaN,NaN,NaN,True

In [58]:
final.to_csv("./data/tickers_all.csv", index=False)

In [62]:
final.groupby(["IsTerminated"]).count()

,ID,Symbol,CompanyName,Exchange,IndustryName1,IndustryName2,IndustryName3,FirstTradeDate,BeforeExchange,DelistedReason
IsTerminated,,,,,,,,,,
False,1552,1552,1552,1552,1552,1552,1552,1546,301,301
True,412,497,495,497,0,493,0,0,412,411

In [85]:
non_financials = final[~((final["IndustryName2"].str.contains("Tài chính", na=False, case=False)) | (final["IndustryName2"].str.contains("Tín dụng", na=False, case=False)) | (final["IndustryName2"].str.contains("Ngân hàng", na=False, case=False)) | (final["IndustryName2"].str.contains("Bảo hiểm", na=False, case=False) | (final["CompanyName"].str.contains("Quản lý quỹ", na=False, case=False)) | (final["CompanyName"].str.contains("Đầu tư tài chính", na=False, case=False))))]
non_financials

,ID,Symbol,CompanyName,Exchange,IndustryName1,IndustryName2,IndustryName3,FirstTradeDate,BeforeExchange,DelistedReason,IsTerminated
0,4712.0,A32,CTCP 32,UPCOM,Tiêu dùng không thiết yếu,Thời trang và hàng lâu bền,Thời trang và dệt may,2018-10-22 17:00:00,NaN,NaN,False
1,2541.0,AAA,CTCP Nhựa An Phát Xanh,HOSE,Nguyên vật liệu,Nguyên vật liệu,Hóa chất,2016-11-24 17:00:00,HNX,"AAA: Ngày 18/11/2016, ngày hủy niêm yết cổ phi...",False
2,5601.0,AAH,CTCP Hợp Nhất,UPCOM,Năng lượng,Năng lượng,Dầu khí,2024-01-10 17:00:00,NaN,NaN,False
3,1813.0,AAM,CTCP Thủy sản MeKong,HOSE,Tiêu dùng thiết yếu,"Thực phẩm, đồ uống và thuốc lá",Thực phẩm,2009-09-23 17:00:00,NaN,NaN,False
4,5816.0,AAN,CTCP Lương thực A An,HOSE,Tiêu dùng thiết yếu,"Thực phẩm, đồ uống và thuốc lá",Thực phẩm,2026-05-21 17:00:00,NaN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...
2042,NaN,VED,Công ty cổ phần Phát triển Thể thao Điện tử Vi...,OTC,NaN,Công nghệ,NaN,NaN,NaN,NaN,True
2045,NaN,VHW,CTCP Nước Khoáng Vĩnh Hảo,OTC,NaN,Hàng tiêu dùng,NaN,NaN,NaN,NaN,True
2046,NaN,VLD,Công ty Cổ phần Bất Động Sản Viettronics,OTC,NaN,,NaN,NaN,NaN,NaN,True
2047,NaN,VTT,NaN,HNX,NaN,NaN,NaN,NaN,NaN,NaN,True
2048,NaN,YAN,CTCP Công nghệ và Tầm nhìn Yêu âm nhạc,OTC,NaN,Dịch vụ,NaN,NaN,NaN,NaN,True

In [86]:
non_financials[(non_financials["IndustryName2"].isna()) | (non_financials["IndustryName2"]).eq("")]

,ID,Symbol,CompanyName,Exchange,IndustryName1,IndustryName2,IndustryName3,FirstTradeDate,BeforeExchange,DelistedReason,IsTerminated
1965,NaN,ABA,NaN,OTC,NaN,NaN,NaN,NaN,NaN,NaN,True
1970,NaN,BJC,Công Ty Cổ Phần VRG - Bảo Lộc,OTC,NaN,,NaN,NaN,NaN,NaN,True
1974,NaN,BTL,Công ty Cổ phần Đầu tư Địa ốc Bến Thành,OTC,NaN,,NaN,NaN,NaN,NaN,True
1977,NaN,DAF,Ngân hàng Thương mại cổ phần Đông Á,OTC,NaN,,NaN,NaN,NaN,NaN,True
1979,NaN,DJL,Công ty TNHH Đầu tư Bất động sản Doji Land,OTC,NaN,NaN,NaN,NaN,NaN,NaN,True
1980,NaN,DNV,CTCP Thương mại Dịch vụ VDA Đà Nẵng,OTC,NaN,,NaN,NaN,NaN,NaN,True
1981,NaN,DTS,CTCP Dịch Vụ Du Lịch Đà Lạt,OTC,NaN,,NaN,NaN,NaN,NaN,True
1982,NaN,DVS,Công ty Cổ phần Thép Đình Vũ,OTC,NaN,,NaN,NaN,NaN,NaN,True
1984,NaN,EPS,Công ty Cổ Phần Chứng khoán Gia Quyền,OTC,NaN,,NaN,NaN,NaN,NaN,True
1987,NaN,FHH,CTCP Đầu tư Kinh doanh Phát triển Bất Động Sản...,OTC,NaN,NaN,NaN,NaN,NaN,NaN,True
1988,NaN,FIS,Công ty Cổ phần Hệ thống Thông tin FPT,OTC,NaN,,NaN,NaN,NaN,NaN,True
1990,NaN,FTG,Công ty cổ phần Thương mại FPT,OTC,NaN,,NaN,NaN,NaN,NaN,True
1992,NaN,GDC,CTCP Xuất Nhập khẩu Gia Định,OTC,NaN,,NaN,NaN,NaN,NaN,True
1994,NaN,GMS,CTCP Thiết kế và gia công phần mền GMS888,OTC,NaN,,NaN,NaN,NaN,NaN,True
1995,NaN,GSC,Công ty cổ phần Thủy điện Geruco Sông Côn,OTC,NaN,,NaN,NaN,NaN,NaN,True
1996,NaN,HIS,Công ty cổ phần Đầu tư phát triển thương mại t...,OTC,NaN,,NaN,NaN,NaN,NaN,True
1999,NaN,ICA,Công ty Cổ phần Công nghệ Sinh học - Dược phẩm...,OTC,NaN,,NaN,NaN,NaN,NaN,True
2004,NaN,KAL,Công ty cổ phần Nhôm Khánh Hoà,OTC,NaN,,NaN,NaN,NaN,NaN,True
2011,NaN,MLG,Công ty Cổ phần Tập đoàn Mai Linh,OTC,NaN,,NaN,NaN,NaN,NaN,True
2015,NaN,NPM,Công ty TNHH Khai thác Chế biến Khoáng sản Núi...,OTC,NaN,,NaN,NaN,NaN,NaN,True
2031,NaN,SPT,Công ty cổ phần Dịch vụ Bưu chính Viễn thông S...,OTC,NaN,,NaN,NaN,NaN,NaN,True
2032,NaN,STJ,Công ty Cổ phần Vận tải Sonadezi,OTC,NaN,,NaN,NaN,NaN,NaN,True
2033,NaN,SVJ,CTCP Santomas Việt Nam,OTC,NaN,,NaN,NaN,NaN,NaN,True
2035,NaN,TDL,CTCP Da Tây Đô,OTC,NaN,,NaN,NaN,NaN,NaN,True
2038,NaN,TKR,Công ty Cổ phần Cao su Tân Biên - Kampong Thom,OTC,NaN,,NaN,NaN,NaN,NaN,True
2046,NaN,VLD,Công ty Cổ phần Bất Động Sản Viettronics,OTC,NaN,,NaN,NaN,NaN,NaN,True
2047,NaN,VTT,NaN,HNX,NaN,NaN,NaN,NaN,NaN,NaN,True

In [87]:
non_financials.to_csv("./data/tickers_non_financials.csv", index=False)