In [ ]:
# Paths come from `paths.py`, never from a literal relative to some checkout.
# That module is the only place that knows where the tree lives, and it names
# the environment variables that override each location (FSCORE_DB above all —
# fscore.db is ~1.7 GB and is not kept in the repository).
# Run this notebook from its own directory, src/fscore_vietnam.
import sys, pathlib

HERE = pathlib.Path.cwd()
assert (HERE / "paths.py").exists(), f"run from src/fscore_vietnam (cwd={HERE})"
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))

from paths import DATA, RESULTS, DB, ensure_dirs, require_db
ensure_dirs()

In [385]:
import accounting_checks_util as ac
import pandas as pd
import importlib
importlib.reload(ac)


field_extract_df = pd.read_csv(RESULTS / "f_score_fields_extract.csv")
field_extract_df

,symbol,period,owner_equity,minority_interest,paid_in_capital,treasury_stock,total_assets,long_term_debt,current_assets,current_liabilities,...,cash_end,cfo_direct,cfi_direct,cff_direct,fx_effect_direct,net_cash_flow_direct,cash_begin_direct,cash_end_direct,paid_in_capital_prev,d_paid_in_capital
0,A32,2016,1.628425e+11,0.0,6.800000e+10,0.0,4.650048e+11,2.429378e+09,3.432787e+11,2.991735e+11,...,1.397735e+11,-3.127942e+10,-8.319863e+09,-9.400540e+10,0.0,-1.336047e+11,2.733782e+11,1.397735e+11,NaN,NaN
1,A32,2017,1.763000e+11,0.0,6.800000e+10,0.0,5.009923e+11,2.429378e+09,3.741267e+11,3.222796e+11,...,1.456583e+11,-6.679452e+09,-2.375775e+09,1.494000e+10,0.0,5.884773e+09,1.397735e+11,1.456583e+11,6.800000e+10,0.0
2,A32,2018,2.008266e+11,0.0,6.800000e+10,0.0,4.688411e+11,2.429378e+09,3.358630e+11,2.656000e+11,...,5.829081e+10,5.224003e+10,3.452162e+09,-1.430597e+11,0.0,-8.736751e+10,1.456583e+11,5.829081e+10,6.800000e+10,0.0
3,A32,2019,2.236159e+11,0.0,6.800000e+10,0.0,4.349303e+11,1.429378e+09,2.987680e+11,2.098882e+11,...,6.051375e+10,1.120983e+10,9.204970e+08,-9.907377e+09,NaN,2.222948e+09,5.829081e+10,6.051375e+10,6.800000e+10,0.0
4,A32,2020,2.422229e+11,0.0,6.800000e+10,0.0,4.882955e+11,0.000000e+00,3.566913e+11,2.460785e+11,...,4.435908e+10,4.279751e+09,3.292742e+09,-2.368176e+10,-45406231.0,-1.610927e+10,6.051375e+10,4.435908e+10,6.800000e+10,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23488,VTR,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23489,VW3,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23490,VXP,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.629632e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23491,X18,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.167372e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23492,VEE,2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.218471e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [386]:
field_extract_df.set_index(keys=["symbol", "period"], inplace=True)
field_extract_df

               owner_equity  minority_interest  paid_in_capital  \
symbol period
A32    2016    1.628425e+11                0.0     6.800000e+10
       2017    1.763000e+11                0.0     6.800000e+10
       2018    2.008266e+11                0.0     6.800000e+10
       2019    2.236159e+11                0.0     6.800000e+10
       2020    2.422229e+11                0.0     6.800000e+10
...                     ...                ...              ...
VTR    2016             NaN                NaN              NaN
VW3    2016             NaN                NaN              NaN
VXP    2015             NaN                NaN              NaN
X18    2010             NaN                NaN              NaN
VEE    2009             NaN                NaN              NaN

               treasury_stock  total_assets  long_term_debt  current_assets  \
symbol period
A32    2016               0.0  4.650048e+11    2.429378e+09    3.432787e+11
       2017               0.0  5.009923e+11    2.429378e+09    3.741267e+11
       2018               0.0  4.688411e+11    2.429378e+09    3.358630e+11
       2019               0.0  4.349303e+11    1.429378e+09    2.987680e+11
       2020               0.0  4.882955e+11    0.000000e+00    3.566913e+11
...                       ...           ...             ...             ...
VTR    2016               NaN           NaN             NaN             NaN
VW3    2016               NaN           NaN             NaN             NaN
VXP    2015               NaN           NaN             NaN             NaN
X18    2010               NaN           NaN             NaN             NaN
VEE    2009               NaN           NaN             NaN             NaN

               current_liabilities  total_liabilities  equity_section  ...  \
symbol period                                                          ...
A32    2016           2.991735e+11       3.016029e+11    1.634019e+11  ...
       2017           3.222796e+11       3.247090e+11    1.762833e+11  ...
       2018           2.656000e+11       2.680293e+11    2.008118e+11  ...
       2019           2.098882e+11       2.113176e+11    2.236127e+11  ...
       2020           2.460785e+11       2.460785e+11    2.422169e+11  ...
...                            ...                ...             ...  ...
VTR    2016                    NaN                NaN             NaN  ...
VW3    2016                    NaN                NaN             NaN  ...
VXP    2015                    NaN                NaN             NaN  ...
X18    2010                    NaN                NaN             NaN  ...
VEE    2009                    NaN                NaN             NaN  ...

                   cash_end    cfo_direct    cfi_direct    cff_direct  \
symbol period
A32    2016    1.397735e+11 -3.127942e+10 -8.319863e+09 -9.400540e+10
       2017    1.456583e+11 -6.679452e+09 -2.375775e+09  1.494000e+10
       2018    5.829081e+10  5.224003e+10  3.452162e+09 -1.430597e+11
       2019    6.051375e+10  1.120983e+10  9.204970e+08 -9.907377e+09
       2020    4.435908e+10  4.279751e+09  3.292742e+09 -2.368176e+10
...                     ...           ...           ...           ...
VTR    2016             NaN           NaN           NaN           NaN
VW3    2016             NaN           NaN           NaN           NaN
VXP    2015    2.629632e+10           NaN           NaN           NaN
X18    2010    5.167372e+09           NaN           NaN           NaN
VEE    2009    1.218471e+10           NaN           NaN           NaN

               fx_effect_direct  net_cash_flow_direct  cash_begin_direct  \
symbol period
A32    2016                 0.0         -1.336047e+11       2.733782e+11
       2017                 0.0          5.884773e+09       1.397735e+11
       2018                 0.0         -8.736751e+10       1.456583e+11
       2019                 NaN          2.222948e+09       5.829081e+10
       2020         -45406231.0         -1.610927e+10       6.051375e+10
...                         ...                   ...                ...
VTR    2016                 NaN                   NaN                NaN
VW3    2016                 NaN                   NaN                NaN
VXP    2015                 NaN                   NaN                NaN
X18    2010                 NaN                   NaN                NaN
VEE    2009                 NaN                   NaN                NaN

               cash_end_direct  paid_in_capital_prev  d_paid_in_capital
symbol period
A32    2016       1.397735e+11                   NaN                NaN
       2017       1.456583e+11          6.800000e+10                0.0
       2018       5.829081e+10          6.800000e+10                0.0
       2019       6.051375e+10          6.800000e+10                0.0
       2020       4.435908e+10          6.800000e+10                0.0
...                        ...                   ...                ...
VTR    2016                NaN                   NaN                NaN
VW3    2016                NaN                   NaN                NaN
VXP    2015                NaN                   NaN                NaN
X18    2010                NaN                   NaN                NaN
VEE    2009                NaN                   NaN                NaN

[23493 rows x 38 columns]

In [387]:
res = ac.run_checks(field_extract_df)
res

               balance_identity  gross_profit_decomposes  cf_sums_to_net  \
symbol period
A32    2016                True                     True            True
       2017                True                     True            True
       2018                True                     True            True
       2019                True                     True            True
       2020                True                     True            True
...                         ...                      ...             ...
VTR    2016                <NA>                     <NA>            <NA>
VW3    2016                <NA>                     <NA>            <NA>
VXP    2015                <NA>                     <NA>            <NA>
X18    2010                <NA>                     <NA>            <NA>
VEE    2009                <NA>                     <NA>            <NA>

               cf_internal_roll  total_liabilities_identity  \
symbol period
A32    2016                True                        True
       2017                True                        True
       2018                True                        True
       2019                <NA>                        True
       2020                True                        True
...                         ...                         ...
VTR    2016                <NA>                        <NA>
VW3    2016                <NA>                        <NA>
VXP    2015                <NA>                        <NA>
X18    2010                <NA>                        <NA>
VEE    2009                <NA>                        <NA>

               net_income_parent_identity  issuance_nonneg
symbol period
A32    2016                          True             <NA>
       2017                          True             True
       2018                          True             True
       2019                          True             True
       2020                          True             True
...                                   ...              ...
VTR    2016                          <NA>             <NA>
VW3    2016                          <NA>             <NA>
VXP    2015                          <NA>             True
X18    2010                          <NA>             True
VEE    2009                          <NA>             True

[23493 rows x 7 columns]

In [388]:
sum = ac.summary(res)
sum

,severity,framework,tested,failed,fail_pct,not_applicable
check,,,,,,
cf_internal_roll,hard,universal,22319,125,0.560,1174
issuance_nonneg,hard,universal,21649,60,0.277,1844
balance_identity,hard,universal,23385,26,0.111,108
cf_sums_to_net,hard,universal,23044,24,0.104,449
net_income_parent_identity,hard,universal,23303,14,0.060,190
total_liabilities_identity,hard,universal,23382,10,0.043,111
gross_profit_decomposes,hard,universal,23299,5,0.021,194

In [389]:
res

               balance_identity  gross_profit_decomposes  cf_sums_to_net  \
symbol period
A32    2016                True                     True            True
       2017                True                     True            True
       2018                True                     True            True
       2019                True                     True            True
       2020                True                     True            True
...                         ...                      ...             ...
VTR    2016                <NA>                     <NA>            <NA>
VW3    2016                <NA>                     <NA>            <NA>
VXP    2015                <NA>                     <NA>            <NA>
X18    2010                <NA>                     <NA>            <NA>
VEE    2009                <NA>                     <NA>            <NA>

               cf_internal_roll  total_liabilities_identity  \
symbol period
A32    2016                True                        True
       2017                True                        True
       2018                True                        True
       2019                <NA>                        True
       2020                True                        True
...                         ...                         ...
VTR    2016                <NA>                        <NA>
VW3    2016                <NA>                        <NA>
VXP    2015                <NA>                        <NA>
X18    2010                <NA>                        <NA>
VEE    2009                <NA>                        <NA>

               net_income_parent_identity  issuance_nonneg
symbol period
A32    2016                          True             <NA>
       2017                          True             True
       2018                          True             True
       2019                          True             True
       2020                          True             True
...                                   ...              ...
VTR    2016                          <NA>             <NA>
VW3    2016                          <NA>             <NA>
VXP    2015                          <NA>             True
X18    2010                          <NA>             True
VEE    2009                          <NA>             True

[23493 rows x 7 columns]

In [390]:
df_test = ac.not_applicable(res, "cf_sums_to_net", field_extract_df)
df_test

                        cfo           cfi           cff  net_cash_flow  \
symbol period
ACM    2021   -1.722948e+09  2.043000e+04           NaN  -1.722928e+09
       2023    7.649442e+08  2.621200e+04           NaN   7.649704e+08
       2024   -1.831612e+08  5.622800e+04           NaN  -1.831050e+08
       2025    3.425132e+08           NaN           NaN   3.425132e+08
AG1    2015             NaN           NaN           NaN            NaN
...                     ...           ...           ...            ...
VTR    2016             NaN           NaN           NaN            NaN
VW3    2016             NaN           NaN           NaN            NaN
VXP    2015    2.064800e+10 -1.211912e+09 -6.640000e+08   1.877209e+10
X18    2010    4.934933e+10 -2.523403e+11  1.800643e+11  -2.292676e+10
VEE    2009    7.151561e+09 -7.236770e+09  7.796310e+09   7.711102e+09

               total_assets
symbol period
ACM    2021    5.338249e+11
       2023    5.337013e+11
       2024    5.857850e+11
       2025    5.308877e+11
AG1    2015    1.294541e+11
...                     ...
VTR    2016             NaN
VW3    2016             NaN
VXP    2015             NaN
X18    2010             NaN
VEE    2009             NaN

[449 rows x 5 columns]

In [391]:
field_extract_df["inferred_net_cash_flow"] = field_extract_df[["cfo", "cff", "cfi"]].sum(axis=1)
field_extract_df

               owner_equity  minority_interest  paid_in_capital  \
symbol period
A32    2016    1.628425e+11                0.0     6.800000e+10
       2017    1.763000e+11                0.0     6.800000e+10
       2018    2.008266e+11                0.0     6.800000e+10
       2019    2.236159e+11                0.0     6.800000e+10
       2020    2.422229e+11                0.0     6.800000e+10
...                     ...                ...              ...
VTR    2016             NaN                NaN              NaN
VW3    2016             NaN                NaN              NaN
VXP    2015             NaN                NaN              NaN
X18    2010             NaN                NaN              NaN
VEE    2009             NaN                NaN              NaN

               treasury_stock  total_assets  long_term_debt  current_assets  \
symbol period
A32    2016               0.0  4.650048e+11    2.429378e+09    3.432787e+11
       2017               0.0  5.009923e+11    2.429378e+09    3.741267e+11
       2018               0.0  4.688411e+11    2.429378e+09    3.358630e+11
       2019               0.0  4.349303e+11    1.429378e+09    2.987680e+11
       2020               0.0  4.882955e+11    0.000000e+00    3.566913e+11
...                       ...           ...             ...             ...
VTR    2016               NaN           NaN             NaN             NaN
VW3    2016               NaN           NaN             NaN             NaN
VXP    2015               NaN           NaN             NaN             NaN
X18    2010               NaN           NaN             NaN             NaN
VEE    2009               NaN           NaN             NaN             NaN

               current_liabilities  total_liabilities  equity_section  ...  \
symbol period                                                          ...
A32    2016           2.991735e+11       3.016029e+11    1.634019e+11  ...
       2017           3.222796e+11       3.247090e+11    1.762833e+11  ...
       2018           2.656000e+11       2.680293e+11    2.008118e+11  ...
       2019           2.098882e+11       2.113176e+11    2.236127e+11  ...
       2020           2.460785e+11       2.460785e+11    2.422169e+11  ...
...                            ...                ...             ...  ...
VTR    2016                    NaN                NaN             NaN  ...
VW3    2016                    NaN                NaN             NaN  ...
VXP    2015                    NaN                NaN             NaN  ...
X18    2010                    NaN                NaN             NaN  ...
VEE    2009                    NaN                NaN             NaN  ...

                 cfo_direct    cfi_direct    cff_direct  fx_effect_direct  \
symbol period
A32    2016   -3.127942e+10 -8.319863e+09 -9.400540e+10               0.0
       2017   -6.679452e+09 -2.375775e+09  1.494000e+10               0.0
       2018    5.224003e+10  3.452162e+09 -1.430597e+11               0.0
       2019    1.120983e+10  9.204970e+08 -9.907377e+09               NaN
       2020    4.279751e+09  3.292742e+09 -2.368176e+10       -45406231.0
...                     ...           ...           ...               ...
VTR    2016             NaN           NaN           NaN               NaN
VW3    2016             NaN           NaN           NaN               NaN
VXP    2015             NaN           NaN           NaN               NaN
X18    2010             NaN           NaN           NaN               NaN
VEE    2009             NaN           NaN           NaN               NaN

               net_cash_flow_direct  cash_begin_direct  cash_end_direct  \
symbol period
A32    2016           -1.336047e+11       2.733782e+11     1.397735e+11
       2017            5.884773e+09       1.397735e+11     1.456583e+11
       2018           -8.736751e+10       1.456583e+11     5.829081e+10
       2019            2.222948e+09       5.829081e+10     6.051375e+10
       2020           -1.610927e+10       6.051375e+10     4.435908e+10
...                             ...                ...              ...
VTR    2016                     NaN                NaN              NaN
VW3    2016                     NaN                NaN              NaN
VXP    2015                     NaN                NaN              NaN
X18    2010                     NaN                NaN              NaN
VEE    2009                     NaN                NaN              NaN

               paid_in_capital_prev  d_paid_in_capital  inferred_net_cash_flow
symbol period
A32    2016                     NaN                NaN           -1.336047e+11
       2017            6.800000e+10                0.0            5.884773e+09
       2018            6.800000e+10                0.0           -8.736751e+10
       2019            6.800000e+10                0.0            2.222948e+09
       2020            6.800000e+10                0.0           -1.610927e+10
...                             ...                ...                     ...
VTR    2016                     NaN                NaN            0.000000e+00
VW3    2016                     NaN                NaN            0.000000e+00
VXP    2015                     NaN                NaN            1.877209e+10
X18    2010                     NaN                NaN           -2.292676e+10
VEE    2009                     NaN                NaN            7.711102e+09

[23493 rows x 39 columns]

In [392]:
fx_effect_inferrable_mask = ((field_extract_df["inferred_net_cash_flow"] == field_extract_df["net_cash_flow"]) & field_extract_df["fx_effect"].isna())
field_extract_df.loc[fx_effect_inferrable_mask, "fx_effect"] = 0
field_extract_df

               owner_equity  minority_interest  paid_in_capital  \
symbol period
A32    2016    1.628425e+11                0.0     6.800000e+10
       2017    1.763000e+11                0.0     6.800000e+10
       2018    2.008266e+11                0.0     6.800000e+10
       2019    2.236159e+11                0.0     6.800000e+10
       2020    2.422229e+11                0.0     6.800000e+10
...                     ...                ...              ...
VTR    2016             NaN                NaN              NaN
VW3    2016             NaN                NaN              NaN
VXP    2015             NaN                NaN              NaN
X18    2010             NaN                NaN              NaN
VEE    2009             NaN                NaN              NaN

               treasury_stock  total_assets  long_term_debt  current_assets  \
symbol period
A32    2016               0.0  4.650048e+11    2.429378e+09    3.432787e+11
       2017               0.0  5.009923e+11    2.429378e+09    3.741267e+11
       2018               0.0  4.688411e+11    2.429378e+09    3.358630e+11
       2019               0.0  4.349303e+11    1.429378e+09    2.987680e+11
       2020               0.0  4.882955e+11    0.000000e+00    3.566913e+11
...                       ...           ...             ...             ...
VTR    2016               NaN           NaN             NaN             NaN
VW3    2016               NaN           NaN             NaN             NaN
VXP    2015               NaN           NaN             NaN             NaN
X18    2010               NaN           NaN             NaN             NaN
VEE    2009               NaN           NaN             NaN             NaN

               current_liabilities  total_liabilities  equity_section  ...  \
symbol period                                                          ...
A32    2016           2.991735e+11       3.016029e+11    1.634019e+11  ...
       2017           3.222796e+11       3.247090e+11    1.762833e+11  ...
       2018           2.656000e+11       2.680293e+11    2.008118e+11  ...
       2019           2.098882e+11       2.113176e+11    2.236127e+11  ...
       2020           2.460785e+11       2.460785e+11    2.422169e+11  ...
...                            ...                ...             ...  ...
VTR    2016                    NaN                NaN             NaN  ...
VW3    2016                    NaN                NaN             NaN  ...
VXP    2015                    NaN                NaN             NaN  ...
X18    2010                    NaN                NaN             NaN  ...
VEE    2009                    NaN                NaN             NaN  ...

                 cfo_direct    cfi_direct    cff_direct  fx_effect_direct  \
symbol period
A32    2016   -3.127942e+10 -8.319863e+09 -9.400540e+10               0.0
       2017   -6.679452e+09 -2.375775e+09  1.494000e+10               0.0
       2018    5.224003e+10  3.452162e+09 -1.430597e+11               0.0
       2019    1.120983e+10  9.204970e+08 -9.907377e+09               NaN
       2020    4.279751e+09  3.292742e+09 -2.368176e+10       -45406231.0
...                     ...           ...           ...               ...
VTR    2016             NaN           NaN           NaN               NaN
VW3    2016             NaN           NaN           NaN               NaN
VXP    2015             NaN           NaN           NaN               NaN
X18    2010             NaN           NaN           NaN               NaN
VEE    2009             NaN           NaN           NaN               NaN

               net_cash_flow_direct  cash_begin_direct  cash_end_direct  \
symbol period
A32    2016           -1.336047e+11       2.733782e+11     1.397735e+11
       2017            5.884773e+09       1.397735e+11     1.456583e+11
       2018           -8.736751e+10       1.456583e+11     5.829081e+10
       2019            2.222948e+09       5.829081e+10     6.051375e+10
       2020           -1.610927e+10       6.051375e+10     4.435908e+10
...                             ...                ...              ...
VTR    2016                     NaN                NaN              NaN
VW3    2016                     NaN                NaN              NaN
VXP    2015                     NaN                NaN              NaN
X18    2010                     NaN                NaN              NaN
VEE    2009                     NaN                NaN              NaN

               paid_in_capital_prev  d_paid_in_capital  inferred_net_cash_flow
symbol period
A32    2016                     NaN                NaN           -1.336047e+11
       2017            6.800000e+10                0.0            5.884773e+09
       2018            6.800000e+10                0.0           -8.736751e+10
       2019            6.800000e+10                0.0            2.222948e+09
       2020            6.800000e+10                0.0           -1.610927e+10
...                             ...                ...                     ...
VTR    2016                     NaN                NaN            0.000000e+00
VW3    2016                     NaN                NaN            0.000000e+00
VXP    2015                     NaN                NaN            1.877209e+10
X18    2010                     NaN                NaN           -2.292676e+10
VEE    2009                     NaN                NaN            7.711102e+09

[23493 rows x 39 columns]

In [393]:
res = ac.run_checks(field_extract_df)
sum = ac.summary(res)
sum

,severity,framework,tested,failed,fail_pct,not_applicable
check,,,,,,
cf_internal_roll,hard,universal,23042,132,0.573,451
issuance_nonneg,hard,universal,21649,60,0.277,1844
balance_identity,hard,universal,23385,26,0.111,108
cf_sums_to_net,hard,universal,23044,24,0.104,449
net_income_parent_identity,hard,universal,23303,14,0.060,190
total_liabilities_identity,hard,universal,23382,10,0.043,111
gross_profit_decomposes,hard,universal,23299,5,0.021,194

In [394]:
res.columns

Index(['balance_identity', 'gross_profit_decomposes', 'cf_sums_to_net',
       'cf_internal_roll', 'total_liabilities_identity',
       'net_income_parent_identity', 'issuance_nonneg'],
      dtype='str')

In [395]:
df_clean = res[res.fillna(False).all(axis=1)]
df_clean

               balance_identity  gross_profit_decomposes  cf_sums_to_net  \
symbol period
A32    2017                True                     True            True
       2018                True                     True            True
       2019                True                     True            True
       2020                True                     True            True
       2021                True                     True            True
...                         ...                      ...             ...
YTC    2021                True                     True            True
       2022                True                     True            True
       2023                True                     True            True
       2024                True                     True            True
       2025                True                     True            True

               cf_internal_roll  total_liabilities_identity  \
symbol period
A32    2017                True                        True
       2018                True                        True
       2019                True                        True
       2020                True                        True
       2021                True                        True
...                         ...                         ...
YTC    2021                True                        True
       2022                True                        True
       2023                True                        True
       2024                True                        True
       2025                True                        True

               net_income_parent_identity  issuance_nonneg
symbol period
A32    2017                          True             True
       2018                          True             True
       2019                          True             True
       2020                          True             True
       2021                          True             True
...                                   ...              ...
YTC    2021                          True             True
       2022                          True             True
       2023                          True             True
       2024                          True             True
       2025                          True             True

[21233 rows x 7 columns]

In [396]:
df_holdout = res[~res.index.isin(df_clean.index)]
df_holdout

               balance_identity  gross_profit_decomposes  cf_sums_to_net  \
symbol period
A32    2016                True                     True            True
AAT    2018                True                     True            True
       2021                True                     True            True
       2023                True                     True            True
AAV    2018                True                     True            True
...                         ...                      ...             ...
VTR    2016                <NA>                     <NA>            <NA>
VW3    2016                <NA>                     <NA>            <NA>
VXP    2015                <NA>                     <NA>            <NA>
X18    2010                <NA>                     <NA>            <NA>
VEE    2009                <NA>                     <NA>            <NA>

               cf_internal_roll  total_liabilities_identity  \
symbol period
A32    2016                True                        True
AAT    2018                True                        True
       2021                True                        True
       2023                True                        True
AAV    2018                True                        True
...                         ...                         ...
VTR    2016                <NA>                        <NA>
VW3    2016                <NA>                        <NA>
VXP    2015                <NA>                        <NA>
X18    2010                <NA>                        <NA>
VEE    2009                <NA>                        <NA>

               net_income_parent_identity  issuance_nonneg
symbol period
A32    2016                          True             <NA>
AAT    2018                          True             <NA>
       2021                          True             <NA>
       2023                          True             <NA>
AAV    2018                          True            False
...                                   ...              ...
VTR    2016                          <NA>             <NA>
VW3    2016                          <NA>             <NA>
VXP    2015                          <NA>             True
X18    2010                          <NA>             True
VEE    2009                          <NA>             True

[2260 rows x 7 columns]

In [397]:
df_holdout.index.get_level_values("period").to_series().groupby("period").count()

period
2009    389
2010    222
2011    172
2012    119
2013    136
2014    214
2015    201
2016    199
2017    116
2018     91
2019     56
2020     80
2021     58
2022     63
2023     57
2024     40
2025     47
Name: period, dtype: int64

In [398]:
field_extract_df.to_csv(RESULTS / "f_score_fields_extract_corrected.csv")

In [399]:
df_clean.to_csv(RESULTS / "accounting_clean_bol_matrix.csv")

In [400]:
df_clean.to_csv(RESULTS / "accounting_holdout_bol_matrix.csv")