In [1]:
# Paths come from `paths.py`, never from a literal relative to some checkout.
# That module is the only place that knows where the tree lives, and it names
# the environment variables that override each location (FSCORE_DB above all —
# fscore.db is ~1.7 GB and is not kept in the repository).
# Run this notebook from its own directory, src/fscore_vietnam.
import sys, pathlib

HERE = pathlib.Path.cwd()
assert (HERE / "paths.py").exists(), f"run from src/fscore_vietnam (cwd={HERE})"
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))

from paths import DATA, RESULTS, DB, ensure_dirs, require_db
ensure_dirs()

In [2]:
import pandas as pd

In [3]:
accounting_clean_df = pd.read_csv(RESULTS / "accounting_clean_bol_matrix.csv")
accounting_clean_df.set_index(keys=["symbol", "period"], inplace=True)

In [4]:
df = pd.read_csv(RESULTS / "f_score_fields_extract_corrected.csv")
df.set_index(keys=["symbol", "period"], inplace=True)

In [5]:
df.loc[("TNG", 2025)]

owner_equity               2.002392e+12
minority_interest          0.000000e+00
paid_in_capital            1.287313e+12
treasury_stock             0.000000e+00
total_assets               6.909526e+12
long_term_debt             9.563418e+11
current_assets             3.368332e+12
current_liabilities        3.817787e+12
total_liabilities          4.907134e+12
equity_section             2.002392e+12
long_term_liabilities      1.089347e+12
cash_and_equivalents       3.172382e+11
net_income_parent          3.930946e+11
gross_profit               1.239198e+12
net_sales                  8.698588e+12
operating_profit           4.750032e+11
other_profit               9.652505e+09
pretax_profit              4.846557e+11
cogs                       7.459391e+12
net_income_total           3.930946e+11
net_income_minority        0.000000e+00
cfo                        4.192046e+11
stock_issuance_proceeds    0.000000e+00
cfi                       -8.800584e+11
cff                        3.328022e+11
fx_effect                  7.274062e+08
net_cash_flow             -1.280517e+11
cash_begin                 4.445625e+11
cash_end                   3.172382e+11
cfo_direct                -2.594863e+11
cfi_direct                -9.059128e+10
cff_direct                 2.218109e+11
fx_effect_direct           9.423999e+08
net_cash_flow_direct      -1.282667e+11
cash_begin_direct          4.445625e+11
cash_end_direct            3.172382e+11
paid_in_capital_prev       1.226012e+12
d_paid_in_capital          6.130060e+10
inferred_net_cash_flow    -1.280517e+11
Name: (TNG, 2025), dtype: float64

In [6]:
df = df.join(accounting_clean_df, how="inner")
df

               owner_equity  minority_interest  paid_in_capital  \
symbol period
A32    2017    1.763000e+11                0.0     6.800000e+10
       2018    2.008266e+11                0.0     6.800000e+10
       2019    2.236159e+11                0.0     6.800000e+10
       2020    2.422229e+11                0.0     6.800000e+10
       2021    2.380572e+11                0.0     6.800000e+10
...                     ...                ...              ...
YTC    2021    2.174660e+10                0.0     3.080000e+10
       2022    3.240305e+10                0.0     3.080000e+10
       2023    3.897662e+10                0.0     3.080000e+10
       2024    1.796766e+11                0.0     9.548000e+10
       2025    1.905966e+11                0.0     9.548000e+10

               treasury_stock  total_assets  long_term_debt  current_assets  \
symbol period
A32    2017               0.0  5.009923e+11    2.429378e+09    3.741267e+11
       2018               0.0  4.688411e+11    2.429378e+09    3.358630e+11
       2019               0.0  4.349303e+11    1.429378e+09    2.987680e+11
       2020               0.0  4.882955e+11    0.000000e+00    3.566913e+11
       2021               0.0  5.281309e+11    0.000000e+00    4.019561e+11
...                       ...           ...             ...             ...
YTC    2021               0.0  7.808035e+11    7.820000e+08    7.218157e+11
       2022               0.0  9.236206e+11    3.155785e+08    8.661802e+11
       2023               0.0  9.401815e+11    2.764484e+10    8.741801e+11
       2024               0.0  1.028879e+12    0.000000e+00    8.948932e+11
       2025               0.0  1.119904e+12    3.120000e+10    9.081023e+11

               current_liabilities  total_liabilities  equity_section  ...  \
symbol period                                                          ...
A32    2017           3.222796e+11       3.247090e+11    1.762833e+11  ...
       2018           2.656000e+11       2.680293e+11    2.008118e+11  ...
       2019           2.098882e+11       2.113176e+11    2.236127e+11  ...
       2020           2.460785e+11       2.460785e+11    2.422169e+11  ...
       2021           2.897457e+11       2.897457e+11    2.383852e+11  ...
...                            ...                ...             ...  ...
YTC    2021           7.582749e+11       7.590569e+11    2.174660e+10  ...
       2022           8.909020e+11       8.912176e+11    3.240305e+10  ...
       2023           8.735601e+11       9.012049e+11    3.897662e+10  ...
       2024           8.492023e+11       8.492023e+11    1.796766e+11  ...
       2025           8.955443e+11       9.293071e+11    1.905966e+11  ...

               paid_in_capital_prev  d_paid_in_capital  \
symbol period
A32    2017            6.800000e+10       0.000000e+00
       2018            6.800000e+10       0.000000e+00
       2019            6.800000e+10       0.000000e+00
       2020            6.800000e+10       0.000000e+00
       2021            6.800000e+10       0.000000e+00
...                             ...                ...
YTC    2021            3.080000e+10       0.000000e+00
       2022            3.080000e+10       0.000000e+00
       2023            3.080000e+10       0.000000e+00
       2024            3.080000e+10       6.468000e+10
       2025            9.548000e+10       0.000000e+00

               inferred_net_cash_flow  balance_identity  \
symbol period
A32    2017              5.884773e+09              True
       2018             -8.736751e+10              True
       2019              2.222948e+09              True
       2020             -1.610927e+10              True
       2021              5.293748e+10              True
...                               ...               ...
YTC    2021             -6.547163e+09              True
       2022              6.745980e+09              True
       2023              1.863278e+10              True
       2024              4.125771e+10              True
       2025             -6.301162e+09              True

               gross_profit_decomposes  cf_sums_to_net  cf_internal_roll  \
symbol period
A32    2017                       True            True              True
       2018                       True            True              True
       2019                       True            True              True
       2020                       True            True              True
       2021                       True            True              True
...                                ...             ...               ...
YTC    2021                       True            True              True
       2022                       True            True              True
       2023                       True            True              True
       2024                       True            True              True
       2025                       True            True              True

               total_liabilities_identity  net_income_parent_identity  \
symbol period
A32    2017                          True                        True
       2018                          True                        True
       2019                          True                        True
       2020                          True                        True
       2021                          True                        True
...                                   ...                         ...
YTC    2021                          True                        True
       2022                          True                        True
       2023                          True                        True
       2024                          True                        True
       2025                          True                        True

               issuance_nonneg
symbol period
A32    2017               True
       2018               True
       2019               True
       2020               True
       2021               True
...                        ...
YTC    2021               True
       2022               True
       2023               True
       2024               True
       2025               True

[21233 rows x 46 columns]

In [7]:
df = df.loc[:, ~df.columns.str.endswith("_direct")]
df

               owner_equity  minority_interest  paid_in_capital  \
symbol period
A32    2017    1.763000e+11                0.0     6.800000e+10
       2018    2.008266e+11                0.0     6.800000e+10
       2019    2.236159e+11                0.0     6.800000e+10
       2020    2.422229e+11                0.0     6.800000e+10
       2021    2.380572e+11                0.0     6.800000e+10
...                     ...                ...              ...
YTC    2021    2.174660e+10                0.0     3.080000e+10
       2022    3.240305e+10                0.0     3.080000e+10
       2023    3.897662e+10                0.0     3.080000e+10
       2024    1.796766e+11                0.0     9.548000e+10
       2025    1.905966e+11                0.0     9.548000e+10

               treasury_stock  total_assets  long_term_debt  current_assets  \
symbol period
A32    2017               0.0  5.009923e+11    2.429378e+09    3.741267e+11
       2018               0.0  4.688411e+11    2.429378e+09    3.358630e+11
       2019               0.0  4.349303e+11    1.429378e+09    2.987680e+11
       2020               0.0  4.882955e+11    0.000000e+00    3.566913e+11
       2021               0.0  5.281309e+11    0.000000e+00    4.019561e+11
...                       ...           ...             ...             ...
YTC    2021               0.0  7.808035e+11    7.820000e+08    7.218157e+11
       2022               0.0  9.236206e+11    3.155785e+08    8.661802e+11
       2023               0.0  9.401815e+11    2.764484e+10    8.741801e+11
       2024               0.0  1.028879e+12    0.000000e+00    8.948932e+11
       2025               0.0  1.119904e+12    3.120000e+10    9.081023e+11

               current_liabilities  total_liabilities  equity_section  ...  \
symbol period                                                          ...
A32    2017           3.222796e+11       3.247090e+11    1.762833e+11  ...
       2018           2.656000e+11       2.680293e+11    2.008118e+11  ...
       2019           2.098882e+11       2.113176e+11    2.236127e+11  ...
       2020           2.460785e+11       2.460785e+11    2.422169e+11  ...
       2021           2.897457e+11       2.897457e+11    2.383852e+11  ...
...                            ...                ...             ...  ...
YTC    2021           7.582749e+11       7.590569e+11    2.174660e+10  ...
       2022           8.909020e+11       8.912176e+11    3.240305e+10  ...
       2023           8.735601e+11       9.012049e+11    3.897662e+10  ...
       2024           8.492023e+11       8.492023e+11    1.796766e+11  ...
       2025           8.955443e+11       9.293071e+11    1.905966e+11  ...

               paid_in_capital_prev  d_paid_in_capital  \
symbol period
A32    2017            6.800000e+10       0.000000e+00
       2018            6.800000e+10       0.000000e+00
       2019            6.800000e+10       0.000000e+00
       2020            6.800000e+10       0.000000e+00
       2021            6.800000e+10       0.000000e+00
...                             ...                ...
YTC    2021            3.080000e+10       0.000000e+00
       2022            3.080000e+10       0.000000e+00
       2023            3.080000e+10       0.000000e+00
       2024            3.080000e+10       6.468000e+10
       2025            9.548000e+10       0.000000e+00

               inferred_net_cash_flow  balance_identity  \
symbol period
A32    2017              5.884773e+09              True
       2018             -8.736751e+10              True
       2019              2.222948e+09              True
       2020             -1.610927e+10              True
       2021              5.293748e+10              True
...                               ...               ...
YTC    2021             -6.547163e+09              True
       2022              6.745980e+09              True
       2023              1.863278e+10              True
       2024              4.125771e+10              True
       2025             -6.301162e+09              True

               gross_profit_decomposes  cf_sums_to_net  cf_internal_roll  \
symbol period
A32    2017                       True            True              True
       2018                       True            True              True
       2019                       True            True              True
       2020                       True            True              True
       2021                       True            True              True
...                                ...             ...               ...
YTC    2021                       True            True              True
       2022                       True            True              True
       2023                       True            True              True
       2024                       True            True              True
       2025                       True            True              True

               total_liabilities_identity  net_income_parent_identity  \
symbol period
A32    2017                          True                        True
       2018                          True                        True
       2019                          True                        True
       2020                          True                        True
       2021                          True                        True
...                                   ...                         ...
YTC    2021                          True                        True
       2022                          True                        True
       2023                          True                        True
       2024                          True                        True
       2025                          True                        True

               issuance_nonneg
symbol period
A32    2017               True
       2018               True
       2019               True
       2020               True
       2021               True
...                        ...
YTC    2021               True
       2022               True
       2023               True
       2024               True
       2025               True

[21233 rows x 39 columns]

In [8]:
df = df.drop(
    columns=accounting_clean_df.columns
)
df

               owner_equity  minority_interest  paid_in_capital  \
symbol period
A32    2017    1.763000e+11                0.0     6.800000e+10
       2018    2.008266e+11                0.0     6.800000e+10
       2019    2.236159e+11                0.0     6.800000e+10
       2020    2.422229e+11                0.0     6.800000e+10
       2021    2.380572e+11                0.0     6.800000e+10
...                     ...                ...              ...
YTC    2021    2.174660e+10                0.0     3.080000e+10
       2022    3.240305e+10                0.0     3.080000e+10
       2023    3.897662e+10                0.0     3.080000e+10
       2024    1.796766e+11                0.0     9.548000e+10
       2025    1.905966e+11                0.0     9.548000e+10

               treasury_stock  total_assets  long_term_debt  current_assets  \
symbol period
A32    2017               0.0  5.009923e+11    2.429378e+09    3.741267e+11
       2018               0.0  4.688411e+11    2.429378e+09    3.358630e+11
       2019               0.0  4.349303e+11    1.429378e+09    2.987680e+11
       2020               0.0  4.882955e+11    0.000000e+00    3.566913e+11
       2021               0.0  5.281309e+11    0.000000e+00    4.019561e+11
...                       ...           ...             ...             ...
YTC    2021               0.0  7.808035e+11    7.820000e+08    7.218157e+11
       2022               0.0  9.236206e+11    3.155785e+08    8.661802e+11
       2023               0.0  9.401815e+11    2.764484e+10    8.741801e+11
       2024               0.0  1.028879e+12    0.000000e+00    8.948932e+11
       2025               0.0  1.119904e+12    3.120000e+10    9.081023e+11

               current_liabilities  total_liabilities  equity_section  ...  \
symbol period                                                          ...
A32    2017           3.222796e+11       3.247090e+11    1.762833e+11  ...
       2018           2.656000e+11       2.680293e+11    2.008118e+11  ...
       2019           2.098882e+11       2.113176e+11    2.236127e+11  ...
       2020           2.460785e+11       2.460785e+11    2.422169e+11  ...
       2021           2.897457e+11       2.897457e+11    2.383852e+11  ...
...                            ...                ...             ...  ...
YTC    2021           7.582749e+11       7.590569e+11    2.174660e+10  ...
       2022           8.909020e+11       8.912176e+11    3.240305e+10  ...
       2023           8.735601e+11       9.012049e+11    3.897662e+10  ...
       2024           8.492023e+11       8.492023e+11    1.796766e+11  ...
       2025           8.955443e+11       9.293071e+11    1.905966e+11  ...

               stock_issuance_proceeds           cfi           cff  \
symbol period
A32    2017               0.000000e+00 -2.375775e+09  1.494000e+10
       2018               0.000000e+00  3.452162e+09 -1.430597e+11
       2019               0.000000e+00  9.204970e+08 -9.907377e+09
       2020               0.000000e+00  3.292742e+09 -2.368176e+10
       2021               0.000000e+00  4.458804e+09 -1.842800e+10
...                                ...           ...           ...
YTC    2021               0.000000e+00 -4.410816e+09 -5.892601e+09
       2022               0.000000e+00 -7.830091e+09 -2.896386e+10
       2023               0.000000e+00 -1.381516e+10  1.139672e+10
       2024               1.288372e+11 -3.325821e+10  5.200693e+10
       2025               0.000000e+00 -8.881424e+10  1.155808e+11

                fx_effect  net_cash_flow    cash_begin      cash_end  \
symbol period
A32    2017           0.0   5.884773e+09  1.397735e+11  1.456583e+11
       2018           0.0  -8.736751e+10  1.456583e+11  5.829081e+10
       2019           0.0   2.222948e+09  5.829081e+10  6.051375e+10
       2020   -45406231.0  -1.610927e+10  6.051375e+10  4.435908e+10
       2021     2680724.0   5.293748e+10  4.435908e+10  9.729924e+10
...                   ...            ...           ...           ...
YTC    2021           0.0  -6.547163e+09  2.481934e+10  1.827217e+10
       2022           0.0   6.745980e+09  1.827217e+10  2.501815e+10
       2023           0.0   1.863278e+10  2.501815e+10  4.365094e+10
       2024           0.0   4.125771e+10  4.365094e+10  8.490865e+10
       2025           0.0  -6.301162e+09  8.490865e+10  7.860749e+10

               paid_in_capital_prev  d_paid_in_capital  inferred_net_cash_flow
symbol period
A32    2017            6.800000e+10       0.000000e+00            5.884773e+09
       2018            6.800000e+10       0.000000e+00           -8.736751e+10
       2019            6.800000e+10       0.000000e+00            2.222948e+09
       2020            6.800000e+10       0.000000e+00           -1.610927e+10
       2021            6.800000e+10       0.000000e+00            5.293748e+10
...                             ...                ...                     ...
YTC    2021            3.080000e+10       0.000000e+00           -6.547163e+09
       2022            3.080000e+10       0.000000e+00            6.745980e+09
       2023            3.080000e+10       0.000000e+00            1.863278e+10
       2024            3.080000e+10       6.468000e+10            4.125771e+10
       2025            9.548000e+10       0.000000e+00           -6.301162e+09

[21233 rows x 32 columns]

In [9]:
df = df.drop(
    columns=["paid_in_capital_prev", "d_paid_in_capital", "inferred_net_cash_flow"]
)
df

               owner_equity  minority_interest  paid_in_capital  \
symbol period
A32    2017    1.763000e+11                0.0     6.800000e+10
       2018    2.008266e+11                0.0     6.800000e+10
       2019    2.236159e+11                0.0     6.800000e+10
       2020    2.422229e+11                0.0     6.800000e+10
       2021    2.380572e+11                0.0     6.800000e+10
...                     ...                ...              ...
YTC    2021    2.174660e+10                0.0     3.080000e+10
       2022    3.240305e+10                0.0     3.080000e+10
       2023    3.897662e+10                0.0     3.080000e+10
       2024    1.796766e+11                0.0     9.548000e+10
       2025    1.905966e+11                0.0     9.548000e+10

               treasury_stock  total_assets  long_term_debt  current_assets  \
symbol period
A32    2017               0.0  5.009923e+11    2.429378e+09    3.741267e+11
       2018               0.0  4.688411e+11    2.429378e+09    3.358630e+11
       2019               0.0  4.349303e+11    1.429378e+09    2.987680e+11
       2020               0.0  4.882955e+11    0.000000e+00    3.566913e+11
       2021               0.0  5.281309e+11    0.000000e+00    4.019561e+11
...                       ...           ...             ...             ...
YTC    2021               0.0  7.808035e+11    7.820000e+08    7.218157e+11
       2022               0.0  9.236206e+11    3.155785e+08    8.661802e+11
       2023               0.0  9.401815e+11    2.764484e+10    8.741801e+11
       2024               0.0  1.028879e+12    0.000000e+00    8.948932e+11
       2025               0.0  1.119904e+12    3.120000e+10    9.081023e+11

               current_liabilities  total_liabilities  equity_section  ...  \
symbol period                                                          ...
A32    2017           3.222796e+11       3.247090e+11    1.762833e+11  ...
       2018           2.656000e+11       2.680293e+11    2.008118e+11  ...
       2019           2.098882e+11       2.113176e+11    2.236127e+11  ...
       2020           2.460785e+11       2.460785e+11    2.422169e+11  ...
       2021           2.897457e+11       2.897457e+11    2.383852e+11  ...
...                            ...                ...             ...  ...
YTC    2021           7.582749e+11       7.590569e+11    2.174660e+10  ...
       2022           8.909020e+11       8.912176e+11    3.240305e+10  ...
       2023           8.735601e+11       9.012049e+11    3.897662e+10  ...
       2024           8.492023e+11       8.492023e+11    1.796766e+11  ...
       2025           8.955443e+11       9.293071e+11    1.905966e+11  ...

               net_income_total  net_income_minority           cfo  \
symbol period
A32    2017        3.544302e+10                  0.0 -6.679452e+09
       2018        4.309588e+10                  0.0  5.224003e+10
       2019        4.696082e+10                  0.0  1.120983e+10
       2020        4.210703e+10                  0.0  4.279751e+09
       2021        3.460926e+10                  0.0  6.690668e+10
...                         ...                  ...           ...
YTC    2021        1.066498e+10                  0.0  3.756254e+09
       2022        3.199633e+10                  0.0  4.353993e+10
       2023        6.573569e+09                  0.0  2.105123e+10
       2024        9.613930e+09                  0.0  2.250899e+10
       2025        1.282963e+10                  0.0 -3.306769e+10

               stock_issuance_proceeds           cfi           cff  \
symbol period
A32    2017               0.000000e+00 -2.375775e+09  1.494000e+10
       2018               0.000000e+00  3.452162e+09 -1.430597e+11
       2019               0.000000e+00  9.204970e+08 -9.907377e+09
       2020               0.000000e+00  3.292742e+09 -2.368176e+10
       2021               0.000000e+00  4.458804e+09 -1.842800e+10
...                                ...           ...           ...
YTC    2021               0.000000e+00 -4.410816e+09 -5.892601e+09
       2022               0.000000e+00 -7.830091e+09 -2.896386e+10
       2023               0.000000e+00 -1.381516e+10  1.139672e+10
       2024               1.288372e+11 -3.325821e+10  5.200693e+10
       2025               0.000000e+00 -8.881424e+10  1.155808e+11

                fx_effect  net_cash_flow    cash_begin      cash_end
symbol period
A32    2017           0.0   5.884773e+09  1.397735e+11  1.456583e+11
       2018           0.0  -8.736751e+10  1.456583e+11  5.829081e+10
       2019           0.0   2.222948e+09  5.829081e+10  6.051375e+10
       2020   -45406231.0  -1.610927e+10  6.051375e+10  4.435908e+10
       2021     2680724.0   5.293748e+10  4.435908e+10  9.729924e+10
...                   ...            ...           ...           ...
YTC    2021           0.0  -6.547163e+09  2.481934e+10  1.827217e+10
       2022           0.0   6.745980e+09  1.827217e+10  2.501815e+10
       2023           0.0   1.863278e+10  2.501815e+10  4.365094e+10
       2024           0.0   4.125771e+10  4.365094e+10  8.490865e+10
       2025           0.0  -6.301162e+09  8.490865e+10  7.860749e+10

[21233 rows x 29 columns]

In [10]:
df.columns

Index(['owner_equity', 'minority_interest', 'paid_in_capital',
       'treasury_stock', 'total_assets', 'long_term_debt', 'current_assets',
       'current_liabilities', 'total_liabilities', 'equity_section',
       'long_term_liabilities', 'cash_and_equivalents', 'net_income_parent',
       'gross_profit', 'net_sales', 'operating_profit', 'other_profit',
       'pretax_profit', 'cogs', 'net_income_total', 'net_income_minority',
       'cfo', 'stock_issuance_proceeds', 'cfi', 'cff', 'fx_effect',
       'net_cash_flow', 'cash_begin', 'cash_end'],
      dtype='str')

## F-score (Piotroski 2000) — two layers

**Layer 1 — raw numbers.** Ratios and year-on-year differences, in the firm's own
units. Nothing is thresholded here, so every number stays inspectable: a signal that
looks wrong can be traced back to the two statement lines it came from.

**Layer 2 — points.** One comparator per raw number turns it into a 0/1 indicator;
the nine indicators sum to the F-score.

| signal | raw (layer 1) | point (layer 2) |
|---|---|---|
| `roa` | `net_income_parent / total_assets[t-1]` | `> 0` |
| `cfoa` | `cfo / total_assets[t-1]` | `> 0` |
| `d_roa` | `roa[t] - roa[t-1]` | `> 0` |
| `accrual` | `roa - cfoa` | `< 0` (cash beats earnings) |
| `d_lever` | `lever[t] - lever[t-1]`, `lever = long_term_debt / mean(total_assets[t], total_assets[t-1])` | `< 0` |
| `d_liquid` | `liquid[t] - liquid[t-1]`, `liquid = current_assets / current_liabilities` | `> 0` |
| `eq_offer` | equity raised during the year (VND) | `<= 0` (did not issue) |
| `d_margin` | `margin[t] - margin[t-1]`, `margin = gross_profit / net_sales` | `> 0` |
| `d_turn` | `turn[t] - turn[t-1]`, `turn = net_sales / total_assets[t-1]` | `> 0` |

Scaling follows the paper: **beginning-of-year** total assets for `roa`, `cfoa` and
`turn`, **average** total assets for `lever`. Both need `t-1`, so a symbol's first
year in the panel scores nothing — and `d_roa`, `d_lever` and `d_turn` need `t-2`,
because the level they difference is itself scaled by the prior year's assets.

**NA is not zero.** A missing raw number yields `<NA>` for that indicator, never a
lost point. `f_score` is only formed where all nine are available (`min_signals`);
`signals_available` says how many there were. Silently scoring a firm 4/9 because
five inputs were missing would put it in the same bucket as a genuinely weak firm.

In [11]:
from dataclasses import dataclass
from typing import Callable

import numpy as np

from statement_fields import FSCORE_INPUTS

FSCORE_INPUTS

{'roa': (('income_statement', 'net_income_parent'),
  ('balance_sheet', 'total_assets')),
 'cfoa': (('cash_flow', 'cfo'), ('balance_sheet', 'total_assets')),
 'd_roa': (('income_statement', 'net_income_parent'),
  ('balance_sheet', 'total_assets')),
 'accrual': (('cash_flow', 'cfo'),
  ('income_statement', 'net_income_parent'),
  ('balance_sheet', 'total_assets')),
 'd_lever': (('balance_sheet', 'long_term_debt'),
  ('balance_sheet', 'total_assets')),
 'd_liquid': (('balance_sheet', 'current_assets'),
  ('balance_sheet', 'current_liabilities')),
 'eq_offer': (('cash_flow', 'stock_issuance_proceeds'),
  ('balance_sheet', 'paid_in_capital')),
 'd_margin': (('income_statement', 'gross_profit'),
  ('income_statement', 'net_sales')),
 'd_turn': (('income_statement', 'net_sales'),
  ('balance_sheet', 'total_assets'))}

In [12]:
# Which FSCORE_INPUTS columns this panel actually carries. A signal is never scored
# off a column that is not there — layer 1 would silently emit all-NaN and layer 2
# would mark it NA, but the report has to be explicit, not inferred from a NaN count.
missing_inputs = {sig: [key for _, key in pairs if key not in df.columns]
                  for sig, pairs in FSCORE_INPUTS.items()}
{sig: cols for sig, cols in missing_inputs.items() if cols}

{}

`d_paid_in_capital` was dropped above, so `eq_offer` rests on the cash-flow line
`stock_issuance_proceeds` alone. That line records **cash** received for shares, and
misses the two Vietnamese issues that raise charter capital without cash — stock
dividends and bonus shares. `ratio_levels` below picks up `d_paid_in_capital`
automatically if that column is joined back in; with it absent, read `eq_offer` as
"did not raise cash equity" rather than Piotroski's "did not issue common equity".

### Layer 1 — raw numbers

Two steps: the level ratios for year `t`, then the differences against the same
symbol's previous year.

Lags are taken **inside this panel**, which is already restricted to firm-years that
passed the accounting checks. A year rejected there is a hole here, and `contiguous`
is what stops `t` being differenced against `t-2` as if nothing were missing.

In [13]:
def _div(num: pd.Series, den: pd.Series) -> pd.Series:
    """num/den with a zero denominator yielding NaN rather than inf."""
    return num / den.replace(0, np.nan)


def contiguity(panel: pd.DataFrame) -> pd.Series:
    """True where the previous row of the same symbol is exactly one year back."""
    year = pd.Series(panel.index.get_level_values("period"), index=panel.index).astype("float")
    return year.sub(year.groupby(level="symbol", sort=False).shift(1)).eq(1)


def _prev(s: pd.Series, contiguous: pd.Series) -> pd.Series:
    """Previous row of the same symbol, NaN where that row is not exactly one year back."""
    return s.groupby(level="symbol", sort=False).shift(1).where(contiguous)

In [14]:
def ratio_levels(panel: pd.DataFrame) -> pd.DataFrame:
    """
    The level ratios the nine signals are built from, one row per firm-year.

    Kept as its own frame because five of the nine signals are differences of these
    levels: computing the level once and lagging it is what makes ROA[t-1] scale by
    total assets at t-2, as the paper defines it, instead of quietly reusing t-1.
    """
    p = panel.sort_index()
    contiguous = contiguity(p)

    ta = p["total_assets"]
    ta_begin = _prev(ta, contiguous)              # beginning-of-year assets
    ta_avg = (ta + ta_begin) / 2

    # Margin and turnover off zero or negative revenue are not small numbers, they are
    # meaningless ones. NaN here so layer 2 reports NA instead of scoring the noise.
    sales = p["net_sales"].where(p["net_sales"] > 0)

    lv = pd.DataFrame(index=p.index)
    lv["contiguous"] = contiguous
    lv["total_assets_begin"] = ta_begin
    lv["roa"] = _div(p["net_income_parent"], ta_begin)
    lv["cfoa"] = _div(p["cfo"], ta_begin)
    lv["lever"] = _div(p["long_term_debt"], ta_avg)
    lv["liquid"] = _div(p["current_assets"], p["current_liabilities"])
    lv["margin"] = _div(p["gross_profit"], sales)
    lv["turn"] = _div(sales, ta_begin)
    lv["equity_raised"] = p["stock_issuance_proceeds"]
    return lv

In [15]:
levels = ratio_levels(df)
levels

               contiguous  total_assets_begin       roa      cfoa     lever  \
symbol period
A32    2017         False                 NaN       NaN       NaN       NaN
       2018          True        5.009923e+11  0.086021  0.104273  0.005010
       2019          True        4.688411e+11  0.100164  0.023910  0.003163
       2020          True        4.349303e+11  0.096813  0.009840  0.000000
       2021          True        4.882955e+11  0.070878  0.137021  0.000000
...                   ...                 ...       ...       ...       ...
YTC    2021          True        9.955348e+11  0.010713  0.003773  0.000880
       2022          True        7.808035e+11  0.040979  0.055763  0.000370
       2023          True        9.236206e+11  0.007117  0.022792  0.029665
       2024          True        9.401815e+11  0.010226  0.023941  0.000000
       2025          True        1.028879e+12  0.012470 -0.032140  0.029040

                 liquid    margin      turn  equity_raised
symbol period
A32    2017    1.160876  0.107159       NaN   0.000000e+00
       2018    1.264545  0.096639  1.289830   0.000000e+00
       2019    1.423463  0.118990  1.474883   0.000000e+00
       2020    1.449502  0.109248  1.675167   0.000000e+00
       2021    1.387272  0.109846  1.331465   0.000000e+00
...                 ...       ...       ...            ...
YTC    2021    0.951918  0.086823  0.606975   0.000000e+00
       2022    0.972251  0.090661  0.871086   0.000000e+00
       2023    1.000710  0.109703  0.602395   0.000000e+00
       2024    1.053805  0.127073  0.737678   1.288372e+11
       2025    1.014023  0.113552  0.890947   0.000000e+00

[21233 rows x 9 columns]

In [16]:
# Levels that are differenced year-on-year. Lagging the level (rather than lagging the
# inputs and recomputing) is what propagates NaN correctly: d_roa needs three
# consecutive years, and roa[t-1] is already NaN when t-2 is missing.
LAGGED_LEVELS = ("roa", "lever", "liquid", "margin", "turn")


def raw_layer(levels: pd.DataFrame) -> pd.DataFrame:
    """The nine raw numbers, same order as FSCORE_INPUTS. No thresholds applied."""
    contiguous = levels["contiguous"]
    prev = {k: _prev(levels[k], contiguous) for k in LAGGED_LEVELS}

    raw = pd.DataFrame(index=levels.index)
    raw["roa"] = levels["roa"]
    raw["cfoa"] = levels["cfoa"]
    raw["d_roa"] = levels["roa"] - prev["roa"]
    raw["accrual"] = levels["roa"] - levels["cfoa"]
    raw["d_lever"] = levels["lever"] - prev["lever"]
    raw["d_liquid"] = levels["liquid"] - prev["liquid"]
    raw["eq_offer"] = levels["equity_raised"]
    raw["d_margin"] = levels["margin"] - prev["margin"]
    raw["d_turn"] = levels["turn"] - prev["turn"]
    return raw

In [17]:
raw = raw_layer(levels)
raw

                    roa      cfoa     d_roa   accrual   d_lever  d_liquid  \
symbol period
A32    2017         NaN       NaN       NaN       NaN       NaN       NaN
       2018    0.086021  0.104273       NaN -0.018252       NaN  0.103669
       2019    0.100164  0.023910  0.014143  0.076254 -0.001847  0.158918
       2020    0.096813  0.009840 -0.003350  0.086973 -0.003163  0.026039
       2021    0.070878  0.137021 -0.025936 -0.066143  0.000000 -0.062230
...                 ...       ...       ...       ...       ...       ...
YTC    2021    0.010713  0.003773  0.026683  0.006940 -0.000481 -0.005420
       2022    0.040979  0.055763  0.030266 -0.014784 -0.000510  0.020333
       2023    0.007117  0.022792 -0.033862 -0.015675  0.029295  0.028459
       2024    0.010226  0.023941  0.003108 -0.013715 -0.029665  0.053095
       2025    0.012470 -0.032140  0.002244  0.044609  0.029040 -0.039782

                   eq_offer  d_margin    d_turn
symbol period
A32    2017    0.000000e+00       NaN       NaN
       2018    0.000000e+00 -0.010520       NaN
       2019    0.000000e+00  0.022351  0.185053
       2020    0.000000e+00 -0.009742  0.200285
       2021    0.000000e+00  0.000598 -0.343703
...                     ...       ...       ...
YTC    2021    0.000000e+00  0.000674 -0.146110
       2022    0.000000e+00  0.003838  0.264112
       2023    0.000000e+00  0.019041 -0.268691
       2024    1.288372e+11  0.017370  0.135282
       2025    0.000000e+00 -0.013520  0.153270

[21233 rows x 9 columns]

### Layer 2 — points

One comparator per raw number. Each rule reads only its own raw column, which is what
keeps the NA rule uniform: an indicator is NA exactly when its raw number is NaN.

In [18]:
@dataclass(frozen=True)
class Signal:
    name: str                                    # matches an FSCORE_INPUTS key
    test: Callable[[pd.Series], pd.Series]       # raw number -> point earned
    note: str


SIGNALS = (
    Signal("roa", lambda x: x > 0,
           "Profitable on beginning-of-year assets."),
    Signal("cfoa", lambda x: x > 0,
           "Operations threw off cash."),
    Signal("d_roa", lambda x: x > 0,
           "Profitability improved. Both years scale by their own beginning assets, "
           "so this needs three consecutive years, not two."),
    Signal("accrual", lambda x: x < 0,
           "CFO exceeds net income. Earnings backed by cash rather than by accruals; "
           "the paper's quality-of-earnings signal."),
    Signal("d_lever", lambda x: x < 0,
           "Long-term leverage fell. Strictly as published: a firm with no long-term "
           "debt in either year has d_lever == 0 and earns nothing here."),
    Signal("d_liquid", lambda x: x > 0,
           "Current ratio improved."),
    Signal("eq_offer", lambda x: x <= 0,
           "Did not raise equity. Issuing shares is read as a signal that internal "
           "funds could not cover the firm's needs."),
    Signal("d_margin", lambda x: x > 0,
           "Gross margin improved."),
    Signal("d_turn", lambda x: x > 0,
           "Asset turnover improved."),
)

# The signal set and FSCORE_INPUTS must not drift apart: FSCORE_INPUTS is what decides
# which statement lines get pulled, so a signal missing there would be scored off
# columns nobody guaranteed were fetched.
assert [s.name for s in SIGNALS] == list(FSCORE_INPUTS), "SIGNALS drifted from FSCORE_INPUTS"

SIGNAL_COLS = [f"f_{s.name}" for s in SIGNALS]


def signals_table() -> pd.DataFrame:
    """The rule set as a frame — for review, export, or the appendix."""
    return pd.DataFrame([{
        "signal": s.name,
        "inputs": ", ".join(k for _, k in FSCORE_INPUTS[s.name]),
        "note": " ".join(s.note.split()),
    } for s in SIGNALS]).set_index("signal")


signals_table()

,inputs,note
signal,,
roa,"net_income_parent, total_assets",Profitable on beginning-of-year assets.
cfoa,"cfo, total_assets",Operations threw off cash.
d_roa,"net_income_parent, total_assets",Profitability improved. Both years scale by th...
accrual,"cfo, net_income_parent, total_assets",CFO exceeds net income. Earnings backed by cas...
d_lever,"long_term_debt, total_assets",Long-term leverage fell. Strictly as published...
d_liquid,"current_assets, current_liabilities",Current ratio improved.
eq_offer,"stock_issuance_proceeds, paid_in_capital",Did not raise equity. Issuing shares is read a...
d_margin,"gross_profit, net_sales",Gross margin improved.
d_turn,"net_sales, total_assets",Asset turnover improved.

In [19]:
def score_layer(raw: pd.DataFrame, signals=SIGNALS, min_signals: int = 9) -> pd.DataFrame:
    """
    Raw numbers -> f_<signal> indicators + f_score.

    True = point earned, False = not earned, NA = the raw number was missing.
    f_score is the sum of the indicators, and is NA below min_signals available:
    a partial sum is not a low score, and mixing the two would put firms with holes
    in their statements into the same bucket as genuinely weak ones.
    """
    out = {}
    for s in signals:
        point = s.test(raw[s.name]).astype("boolean")
        point[raw[s.name].isna()] = pd.NA
        out[f"f_{s.name}"] = point

    scores = pd.DataFrame(out, index=raw.index)
    available = scores.notna().sum(axis=1)
    total = scores.fillna(False).sum(axis=1).astype("Int64")

    scores["signals_available"] = available
    scores["f_score"] = total.where(available >= min_signals)
    return scores

In [20]:
scores = score_layer(raw)
scores

               f_roa  f_cfoa  f_d_roa  f_accrual  f_d_lever  f_d_liquid  \
symbol period
A32    2017     <NA>    <NA>     <NA>       <NA>       <NA>        <NA>
       2018     True    True     <NA>       True       <NA>        True
       2019     True    True     True      False       True        True
       2020     True    True    False      False       True        True
       2021     True    True    False       True      False       False
...              ...     ...      ...        ...        ...         ...
YTC    2021     True    True     True      False       True       False
       2022     True    True     True       True       True        True
       2023     True    True    False       True      False        True
       2024     True    True     True       True       True        True
       2025     True   False     True      False      False       False

               f_eq_offer  f_d_margin  f_d_turn  signals_available  f_score
symbol period
A32    2017          True        <NA>      <NA>                  1     <NA>
       2018          True       False      <NA>                  6     <NA>
       2019          True        True      True                  9        8
       2020          True       False      True                  9        6
       2021          True        True     False                  9        5
...                   ...         ...       ...                ...      ...
YTC    2021          True        True     False                  9        6
       2022          True        True      True                  9        9
       2023          True        True     False                  9        6
       2024         False        True      True                  9        8
       2025          True       False      True                  9        4

[21233 rows x 11 columns]

### Coverage and diagnostics

Read these before using the score. The first table is the one that decides how much of
the panel is actually scoreable; the rest are sanity checks on the nine signals.

In [21]:
coverage = pd.DataFrame({
    "rows": scores["signals_available"].value_counts().sort_index(),
})
coverage["pct"] = (100 * coverage["rows"] / len(scores)).round(2)
coverage.index.name = "signals_available"
coverage

                    rows    pct
signals_available
1                   2388  11.25
5                     24   0.11
6                   2091   9.85
7                    161   0.76
8                      5   0.02
9                  16564  78.01

In [22]:
pd.DataFrame({
    "earned": (scores[SIGNAL_COLS] == True).sum(),      # noqa: E712
    "not_earned": (scores[SIGNAL_COLS] == False).sum(),  # noqa: E712
    "not_applicable": scores[SIGNAL_COLS].isna().sum(),
}).assign(earned_pct=lambda d: (100 * d["earned"] / (d["earned"] + d["not_earned"])).round(2))

            earned  not_earned  not_applicable  earned_pct
f_roa        16239        2606            2388       86.17
f_cfoa       12975        5870            2388       68.85
f_d_roa       8147        8583            4503        48.7
f_accrual    10497        8348            2388        55.7
f_d_lever     6562       10163            4508       39.23
f_d_liquid    9865        8980            2388       52.35
f_eq_offer   18249        2984               0       85.95
f_d_margin    9246        9414            2573       49.55
f_d_turn      8074        8495            4664       48.73

In [23]:
dist = scores["f_score"].value_counts(dropna=False).sort_index().rename("rows").to_frame()
dist["pct"] = (100 * dist["rows"] / len(scores)).round(2)
dist

         rows    pct
f_score
0           2   0.01
1         100   0.47
2         609   2.87
3        1731   8.15
4        2799  13.18
5        3512  16.54
6        3322  15.65
7        2511  11.83
8        1476   6.95
9         502   2.36
<NA>     4669  21.99

In [24]:
scores.groupby(level="period")["f_score"].agg(
    scored="count", mean="mean", high=lambda s: (s >= 8).sum(), low=lambda s: (s <= 1).sum()
).round(2)

        scored  mean  high  low
period
2009         0  <NA>     0    0
2010         0  <NA>     0    0
2011       479  4.79    35   12
2012       666  5.02    50   10
2013       788  5.37    97    3
2014       858  5.57   121    2
2015       931  5.42   103    3
2016      1010   5.4   121    4
2017      1150  5.24   126    9
2018      1266  5.28   123    8
2019      1369  5.45   163    6
2020      1400  5.37   147   11
2021      1399  5.39   188    7
2022      1345  5.43   205    8
2023      1325   5.1   114   13
2024      1307  5.69   208    6
2025      1271  5.68   177    0

In [25]:
# d_lever is the one signal whose zero point is not a judgement about the firm: a
# debt-free firm cannot deleverage, so the published `< 0` rule denies it the point.
#
# d_lever == 0 says the RATIO did not move, which is a weaker claim than "no debt" —
# so the two are counted apart below rather than assumed equal. They coincide in this
# panel for a structural reason: lever = long_term_debt / mean(total_assets[t],
# total_assets[t-1]), so a firm carrying debt would need both years' ratios to agree to
# the last float bit, which average total assets never does. Firms that repaid debt land
# in d_lever < 0 and earn the point; firms that borrowed land in d_lever > 0.
ltd = df["long_term_debt"].sort_index()
ltd_prev = _prev(ltd, levels["contiguous"])

scored = scores["f_score"].notna()
zero = scored & (raw["d_lever"] == 0)

pd.Series({
    "scored_rows": int(scored.sum()),
    "d_lever_negative": int((scored & (raw["d_lever"] < 0)).sum()),
    "d_lever_positive": int((scored & (raw["d_lever"] > 0)).sum()),
    "d_lever_zero": int(zero.sum()),
    "  zero, no debt in either year": int((zero & (ltd == 0) & (ltd_prev == 0)).sum()),
    "  zero, debt outstanding": int((zero & ((ltd > 0) | (ltd_prev > 0))).sum()),
    "mean_f_score": round(scores.loc[scored, "f_score"].mean(), 3),
    "mean_f_score_if_rule_were_le_0": round(
        (scores.loc[scored, "f_score"] + (raw.loc[scored, "d_lever"] == 0)).mean(), 3),
})

scored_rows                       16564.000
d_lever_negative                   6540.000
d_lever_positive                   3551.000
d_lever_zero                       6473.000
  zero, no debt in either year     6473.000
  zero, debt outstanding              0.000
mean_f_score                          5.379
mean_f_score_if_rule_were_le_0        5.770
dtype: float64

In [26]:
# How many names the strategy actually buys under each d_lever rule, at the cutoff in
# use. This is the number that matters: the mean F-score barely moves, but the rule
# decides how many firm-years clear the bar.
#
# Loosening `< 0` to `<= 0` can only ADD points, so the strict selection is a subset of
# the loose one — every difference below is a firm-year crossing the cutoff, none
# leaving it. The assert is what guarantees that reading of the table.
from dataclasses import replace

CUTOFF = 7

SIGNALS_LEVER_LE0 = tuple(replace(s, test=lambda x: x <= 0) if s.name == "d_lever" else s
                          for s in SIGNALS)
scores_le0 = score_layer(raw, signals=SIGNALS_LEVER_LE0)

selected = (scores["f_score"] >= CUTOFF).fillna(False)
selected_le0 = (scores_le0["f_score"] >= CUTOFF).fillna(False)
assert not (selected & ~selected_le0).any(), "loosening dropped a name — rules are not nested"

cutoff_shift = pd.DataFrame({
    "scored": scores["f_score"].notna().groupby(level="period").sum(),
    "d_lever<0": selected.groupby(level="period").sum(),
    "d_lever<=0": selected_le0.groupby(level="period").sum(),
})
cutoff_shift["added"] = cutoff_shift["d_lever<=0"] - cutoff_shift["d_lever<0"]
cutoff_shift["added_pct"] = (100 * cutoff_shift["added"] / cutoff_shift["d_lever<0"]).round(1)

cutoff_shift.loc["ALL"] = cutoff_shift.sum()
cutoff_shift.loc["ALL", "added_pct"] = round(
    100 * cutoff_shift.loc["ALL", "added"] / cutoff_shift.loc["ALL", "d_lever<0"], 1)

# The ALL row makes the index object-typed, which floats the counts. They are names
# held, not quantities: keep them integers.
counts = ["scored", "d_lever<0", "d_lever<=0", "added"]
cutoff_shift[counts] = cutoff_shift[counts].astype(int)
cutoff_shift

        scored  d_lever<0  d_lever<=0  added  added_pct
period
2009         0          0           0      0       <NA>
2010         0          0           0      0       <NA>
2011       479         74          97     23       31.1
2012       666        144         188     44       30.6
2013       788        209         261     52       24.9
2014       858        278         335     57       20.5
2015       931        257         331     74       28.8
2016      1010        277         359     82       29.6
2017      1150        276         361     85       30.8
2018      1266        305         423    118       38.7
2019      1369        361         480    119       33.0
2020      1400        368         483    115       31.2
2021      1399        389         491    102       26.2
2022      1345        414         519    105       25.4
2023      1325        275         390    115       41.8
2024      1307        443         561    118       26.6
2025      1271        419         544    125       29.8
ALL      16564       4489        5823   1334       29.7

### Export

Raw numbers travel with the points. A score without the numbers behind it cannot be
audited, and the raws are what any later robustness check (a different comparator, a
cross-sectional rank instead of a threshold) is rebuilt from.

In [27]:
f_score_panel = raw.add_prefix("raw_").join(scores)
f_score_panel

                raw_roa  raw_cfoa  raw_d_roa  raw_accrual  raw_d_lever  \
symbol period
A32    2017         NaN       NaN        NaN          NaN          NaN
       2018    0.086021  0.104273        NaN    -0.018252          NaN
       2019    0.100164  0.023910   0.014143     0.076254    -0.001847
       2020    0.096813  0.009840  -0.003350     0.086973    -0.003163
       2021    0.070878  0.137021  -0.025936    -0.066143     0.000000
...                 ...       ...        ...          ...          ...
YTC    2021    0.010713  0.003773   0.026683     0.006940    -0.000481
       2022    0.040979  0.055763   0.030266    -0.014784    -0.000510
       2023    0.007117  0.022792  -0.033862    -0.015675     0.029295
       2024    0.010226  0.023941   0.003108    -0.013715    -0.029665
       2025    0.012470 -0.032140   0.002244     0.044609     0.029040

               raw_d_liquid  raw_eq_offer  raw_d_margin  raw_d_turn  f_roa  \
symbol period
A32    2017             NaN  0.000000e+00           NaN         NaN   <NA>
       2018        0.103669  0.000000e+00     -0.010520         NaN   True
       2019        0.158918  0.000000e+00      0.022351    0.185053   True
       2020        0.026039  0.000000e+00     -0.009742    0.200285   True
       2021       -0.062230  0.000000e+00      0.000598   -0.343703   True
...                     ...           ...           ...         ...    ...
YTC    2021       -0.005420  0.000000e+00      0.000674   -0.146110   True
       2022        0.020333  0.000000e+00      0.003838    0.264112   True
       2023        0.028459  0.000000e+00      0.019041   -0.268691   True
       2024        0.053095  1.288372e+11      0.017370    0.135282   True
       2025       -0.039782  0.000000e+00     -0.013520    0.153270   True

               f_cfoa  f_d_roa  f_accrual  f_d_lever  f_d_liquid  f_eq_offer  \
symbol period
A32    2017      <NA>     <NA>       <NA>       <NA>        <NA>        True
       2018      True     <NA>       True       <NA>        True        True
       2019      True     True      False       True        True        True
       2020      True    False      False       True        True        True
       2021      True    False       True      False       False        True
...               ...      ...        ...        ...         ...         ...
YTC    2021      True     True      False       True       False        True
       2022      True     True       True       True        True        True
       2023      True    False       True      False        True        True
       2024      True     True       True       True        True       False
       2025     False     True      False      False       False        True

               f_d_margin  f_d_turn  signals_available  f_score
symbol period
A32    2017          <NA>      <NA>                  1     <NA>
       2018         False      <NA>                  6     <NA>
       2019          True      True                  9        8
       2020         False      True                  9        6
       2021          True     False                  9        5
...                   ...       ...                ...      ...
YTC    2021          True     False                  9        6
       2022          True      True                  9        9
       2023          True     False                  9        6
       2024          True      True                  9        8
       2025         False      True                  9        4

[21233 rows x 20 columns]

In [28]:
f_score_panel.to_csv(RESULTS / "f_score_panel.csv")