In [ ]:
# Paths come from `paths.py`, never from a literal relative to some checkout.
# That module is the only place that knows where the tree lives, and it names
# the environment variables that override each location (FSCORE_DB above all —
# fscore.db is ~1.7 GB and is not kept in the repository).
# Run this notebook from its own directory, src/fscore_vietnam.
import sys, pathlib

HERE = pathlib.Path.cwd()
assert (HERE / "paths.py").exists(), f"run from src/fscore_vietnam (cwd={HERE})"
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))

from paths import DATA, RESULTS, DB, ensure_dirs, require_db
ensure_dirs()

In [1]:
import pandas as pd

import sqlite3

con = sqlite3.connect(require_db())

df = pd.read_sql("select * from fireant_financial_data_general where symbol = 'A32'", con)

df

,symbol,period,Quarter,Year,CompanyType,TotalRevenue,NetSale,CostOfGoodSold,GrossProfit,ProfitFromFinancialActivity,...,NonManufacturingStatus,ManufacturingSPRating,NonManufacturingSPRating,ManufacturingMoodyRating,NonManufacturingMoodyRating,WorkingCapitalOverAsset,RetainedEarningOverAsset,EBITOverAsset,MarketCapOverDebt,NetSaleOverAsset
0,A32,2016,0,2016,General,629259462639,629259462639,563614430007,65645032632,14985781180,...,NaN,NaN,NaN,NaN,NaN,0.09485,0.08385,0.09301,NaN,1.35323
1,A32,2017,0,2017,General,611910105351,611820717623,546258715162,65562002461,13094213597,...,NaN,NaN,NaN,NaN,NaN,0.10349,0.07930,0.08372,NaN,1.22122
2,A32,2018,0,2018,General,646214747621,646194779056,583746959157,62447819899,13828438710,...,An toàn,BBB-,BBB,Baa3,Baa2,0.14987,0.11069,0.10985,0.76618,1.37828
3,A32,2019,0,2019,General,691485702395,691485702395,609205657982,82280044413,11144806050,...,An toàn,BBB,A+,Baa2,A1,0.20435,0.13710,0.13012,0.90101,1.58988
4,A32,2020,0,2020,General,728582496415,728581046415,648984925398,79596121017,8456786583,...,An toàn,BBB,A,Baa2,A2,0.22653,0.12661,0.10359,0.95335,1.49209
5,A32,2021,0,2021,General,650148136248,650148136248,578731775257,71416360991,7232535299,...,An toàn,BB+,BBB,Ba1,Baa2,0.21247,0.08525,0.07905,0.74631,1.23104
6,A32,2022,0,2022,General,719280459321,719280459321,625906575936,93373883385,12266333568,...,Cảnh báo,BB+,BB+,Ba1,Ba1,0.15273,0.04086,0.08010,0.61846,1.31387
7,A32,2023,0,2023,General,719516620989,719516620989,636431780680,83084840309,13864886882,...,An toàn,BBB-,BBB,Baa3,Baa2,0.19340,0.05011,0.09270,0.71981,1.42356
8,A32,2024,0,2024,General,727056756533,727056756533,654718547132,72338209401,18260468925,...,An toàn,BBB,BBB+,Baa2,Baa1,0.19219,0.04934,0.09209,0.94535,1.46608
9,A32,2025,0,2025,General,778316791673,777808047055,697347974282,80460072773,21370830212,...,An toàn,BBB,A,Baa2,A2,0.22451,0.06938,0.12460,0.91147,1.58375

In [13]:
df[df.columns[df.columns.str.contains('share', case=False)]]

,ParentCompanyShareholderProfitAfterTax,ParentCompanyShareholderProfitAfterTax_TTM,ParentCompanyShareholderProfitAfterTax_CUM,ContributedCapitalOfShareHolder,AvgShareInPeriod,ShareAtPeriodEnd,SalePerShare,BookValuePerShare,TangibleBookValuePerShare,ParentCompanyShareholderProfitAfterTaxGrowth
0,36473362657,36473362657,None,68000000000,6800000,6800000,92538.15627,24029.69201,24029.69201,NaN
1,35443022026,35443022026,None,68000000000,6800000,6800000,89973.63494,25924.01564,25902.93843,-0.02825
2,43095883812,43095883812,None,68000000000,6800000,6800000,95028.64398,29531.14351,29512.22806,0.21592
3,46960820197,46960820197,None,68000000000,6800000,6800000,101689.07388,32884.22772,32867.47404,0.08968
4,42107027168,42107027168,None,68000000000,6800000,6800000,107144.27153,35620.13862,35605.54671,-0.10336
5,34609256742,34609256742,None,68000000000,6800000,6800000,95610.02004,35056.64564,35015.90667,-0.17806
6,36666733445,36666733445,None,68000000000,6800000,6800000,105776.53814,31676.43155,31640.94258,0.05945
7,39629185588,39629185588,None,68000000000,6800000,6800000,105811.26779,32650.60813,32607.73687,0.08079
8,39269119523,39269119523,None,68000000000,6800000,6800000,106920.11125,32520.99911,32489.31172,-0.00909
9,50872308164,50872308164,None,68000000000,6800000,6800000,114383.53633,33933.66565,33910.50021,0.29548

In [14]:
df

,symbol,period,Quarter,Year,CompanyType,TotalRevenue,NetSale,CostOfGoodSold,GrossProfit,ProfitFromFinancialActivity,...,NonManufacturingStatus,ManufacturingSPRating,NonManufacturingSPRating,ManufacturingMoodyRating,NonManufacturingMoodyRating,WorkingCapitalOverAsset,RetainedEarningOverAsset,EBITOverAsset,MarketCapOverDebt,NetSaleOverAsset
0,A32,2016,0,2016,General,629259462639,629259462639,563614430007,65645032632,14985781180,...,NaN,NaN,NaN,NaN,NaN,0.09485,0.08385,0.09301,NaN,1.35323
1,A32,2017,0,2017,General,611910105351,611820717623,546258715162,65562002461,13094213597,...,NaN,NaN,NaN,NaN,NaN,0.10349,0.07930,0.08372,NaN,1.22122
2,A32,2018,0,2018,General,646214747621,646194779056,583746959157,62447819899,13828438710,...,An toàn,BBB-,BBB,Baa3,Baa2,0.14987,0.11069,0.10985,0.76618,1.37828
3,A32,2019,0,2019,General,691485702395,691485702395,609205657982,82280044413,11144806050,...,An toàn,BBB,A+,Baa2,A1,0.20435,0.13710,0.13012,0.90101,1.58988
4,A32,2020,0,2020,General,728582496415,728581046415,648984925398,79596121017,8456786583,...,An toàn,BBB,A,Baa2,A2,0.22653,0.12661,0.10359,0.95335,1.49209
5,A32,2021,0,2021,General,650148136248,650148136248,578731775257,71416360991,7232535299,...,An toàn,BB+,BBB,Ba1,Baa2,0.21247,0.08525,0.07905,0.74631,1.23104
6,A32,2022,0,2022,General,719280459321,719280459321,625906575936,93373883385,12266333568,...,Cảnh báo,BB+,BB+,Ba1,Ba1,0.15273,0.04086,0.08010,0.61846,1.31387
7,A32,2023,0,2023,General,719516620989,719516620989,636431780680,83084840309,13864886882,...,An toàn,BBB-,BBB,Baa3,Baa2,0.19340,0.05011,0.09270,0.71981,1.42356
8,A32,2024,0,2024,General,727056756533,727056756533,654718547132,72338209401,18260468925,...,An toàn,BBB,BBB+,Baa2,Baa1,0.19219,0.04934,0.09209,0.94535,1.46608
9,A32,2025,0,2025,General,778316791673,777808047055,697347974282,80460072773,21370830212,...,An toàn,BBB,A,Baa2,A2,0.22451,0.06938,0.12460,0.91147,1.58375